자연어 처리란?

인간의 언어를 컴퓨터가 이해하고 처리할 수 있도록 하는 기술을 연구하는 분야입니다.

NLP는 컴퓨터 과학, 인공지능, 언어학의 교차점에 위치하며, 텍스트 및 음성 데이터를 분석, 해석, 생성하는 다양한 응용 프로그램에서 사용됩니다.
주요 목표는 컴퓨터가 자연어(사람들이 일상에서 사용하는 언어)를 이해하고 상호작용할 수 있도록 하는 것입니다.

In [ ]:
 # NLP에 필요한 spaCy, NLTK, Transformers 등의 라이브러리 동시에 설치

In [ ]:
pip install nltk spacy transformers

    matplotlib-inline (<0.2.0appnope,>=0.1.0) ; platform_system == "Darwin"
                      ~~~~~~~~^


In [ ]:
#  패키지 관리 명령어 요약
# 명령어	설명
# pip install 패키지명	새로운 패키지를 설치합니다.
# pip list	현재 설치된 패키지 목록을 확인합니다.
# pip install --upgrade 패키지명	패키지를 최신 버전으로 업데이트합니다.
# pip uninstall 패키지명	패키지를 삭제합니다.

In [ ]:
# NLTK란?

In [ ]:
# NLTK(Natural Language Toolkit)는 파이썬을 기반으로 자연어 처리(NLP)를 수행할 수 있는 강력한 오픈소스 라이브러리입니다.
# 자연어 처리의 입문자부터 전문가까지 다양한 사용자들이 손쉽게 사용할 수 있도록 다양한 도구와 데이터셋을 제공하며, 텍스트 전처리, 형태소 분석, 문장 분류, 정서 분석 등의 과업을 지원합니다. NLTK는 학습, 연구, 프로토타입 개발에 적합한 다목적 도구 상자로, 다양한 NLP 과업을 체계적으로 처리할 수 있는 모듈을 포함하고 있습니다.

# NLTK의 주요 특징
# 텍스트 전처리: NLTK는 토큰화, 불용어 제거, 어간 추출, 표제어 추출 등 텍스트를 분석하기 전에 필요한 전처리 과정을 쉽게 수행할 수 있는 도구들을 제공합니다.
# 형태소 분석: 단어의 기본 형태를 파악하는 형태소 분석 기능을 제공하여 텍스트에서 단어의 형태나 품사를 쉽게 분석할 수 있습니다.
# 정서 분석: 텍스트에 포함된 정서을 분석하는 데 필요한 도구도 제공하여, 긍정적인지 부정적인지 등의 정서 분석을 쉽게 수행할 수 있습니다.
# 말뭉치(Corpus) 데이터 제공: NLTK는 여러 말뭉치(corpus) 데이터를 포함하고 있어, 학습이나 실습에서 바로 사용할 수 있습니다. 예를 들어, 브라운 코퍼스(Brown Corpus), 워드넷(WordNet) 등 다양한 텍스트 데이터가 내장되어 있어 학습 자료로 유용합니다.
# 분류 및 모델링: NLTK는 기계 학습 기반 분류, 군집화 등의 텍스트 분류 작업을 지원하며, 이를 통해 자연어 처리 모델을 구축할 수 있습니다.

In [ ]:
# NLTK 주요 데이터셋 소개

In [ ]:
# NLTK는 다양한 말뭉치(corpus)를 제공하며, 이를 이용해 자연어 처리 실습 및 연구를 수행할 수 있습니다.
# 다음은 자주 사용하는 데이터셋입니다.

In [ ]:
# nltk.download('wordnet')  # 워드넷(WordNet): 어휘 데이터베이스
# nltk.download('averaged_perceptron_tagger')  # 품사 태깅 데이터
# nltk.download('stopwords')  # 불용어 목록
# nltk.download('movie_reviews')  # 영화 리뷰 말뭉치

In [ ]:
# NLTK(Natural Language Toolkit)는 파이썬 기반의 자연어 처리 라이브러리로, 다양한 텍스트 처리 기능을 제공하며 풍부한 데이터셋을 포함하고 있습니다. 이러한 데이터셋은 자연어 처리 연구와 학습에 널리 사용됩니다. 아래는 NLTK에서 제공하는 주요 데이터셋들에 대한 간략한 소개입니다:

# 1. Brown Corpus
# 설명: Brown Corpus는 최초로 수집된 대규모 언어 코퍼스 중 하나로, 1960년대 미국 영어 텍스트로 구성되어 있습니다. 약 1백만 개의 단어로 구성된 이 코퍼스는 장르별로 문서를 나누어 제공하여 다양한 텍스트 장르(소설, 뉴스, 학술 등)에서의 언어 패턴을 연구할 수 있습니다.
# 용도: 주로 언어 모델링, 품사 태깅 연구에 사용됩니다.
# 2. Gutenberg Corpus
# 설명: Project Gutenberg에서 제공하는 공공 도메인 텍스트로 구성된 코퍼스입니다. 이 코퍼스는 문학 작품들을 포함하고 있으며, 셰익스피어, 제인 오스틴, 마크 트웨인 등 유명 작가들의 작품이 포함되어 있습니다.
# 용도: 자연어 처리 연구, 텍스트 분석, 단어 빈도 분석 등에 자주 사용됩니다.
# 3. WordNet
# 설명: WordNet은 단어의 의미 관계를 중심으로 구성된 어휘 데이터베이스로, 단어 간의 동의어 관계, 하위어-상위어 관계 등을 제공합니다. 각 단어는 의미에 따라 **신셋(synset)**이라는 그룹으로 묶여 있습니다.
# 용도: 의미 분석, 자연어 이해 등의 연구에 널리 사용됩니다.
# 4. Reuters Corpus
# 설명: Reuters 코퍼스는 로이터 통신에서 발행한 뉴스 기사를 모은 데이터셋입니다. 경제, 정치, 스포츠 등 다양한 주제를 다루며, 약 10,000개의 뉴스 기사가 포함되어 있습니다.
# 용도: 텍스트 분류, 정보 검색, 토픽 모델링 등의 연구에 사용됩니다.
# 5. Movie Reviews Corpus
# 설명: 영화 리뷰 데이터를 포함한 코퍼스로, 각 리뷰에는 긍정적 또는 부정적 감정 레이블이 달려 있습니다. 감정 분석 연구에 매우 유용합니다.
# 용도: 감정 분석, 텍스트 분류 연구에 주로 사용됩니다.
# 6. Inaugural Address Corpus
# 설명: 미국 대통령들의 취임 연설 모음집으로, 1789년 조지 워싱턴부터 현대에 이르기까지 다양한 시대의 연설문이 포함되어 있습니다.
# 용도: 언어 변화 분석, 정치적 담론 연구, 텍스트 분석 등에서 활용됩니다.
# 7. Names Corpus
# 설명: 사람의 이름과 성별이 매핑된 데이터셋입니다. 약 8,000개의 이름이 남성과 여성으로 분류되어 있습니다.
# 용도: 성별 예측, 텍스트 분류 및 의미론적 연구에 사용됩니다.
# 8. Conll2000 Chunking Corpus
# 설명: 이 코퍼스는 텍스트에서 **문법적 단위(chunk)**를 예측하는 문제에 사용됩니다. 명사구, 동사구 등 문장의 다양한 문법적 요소를 분석하는 데 유용합니다.
# 용도: 구문 분석, POS 태깅, 문법적 구조 학습에 사용됩니다.
# 9. Twitter Samples
# 설명: NLTK는 트위터 데이터를 제공하는데, 이는 소셜 미디어에서 사용되는 짧은 문장의 특성을 분석하는 데 유용합니다. 다양한 트윗 데이터를 통해 감정 분석, 키워드 분석 등을 수행할 수 있습니다.
# 용도: 감정 분석, 트렌드 분석, 소셜 미디어 연구에 사용됩니다.
# 10. Stopwords
# 설명: NLTK는 영어를 포함한 여러 언어에서 자주 사용되지만 의미가 없는 불용어(stopwords) 리스트를 제공합니다.
# 용도: 텍스트 전처리, 단어 빈도 분석에서 중요하지 않은 단어들을 제거하는 데 사용됩니다.


In [1]:
# 설치 확인을 위한 간단한 예시
import nltk
from nltk.tokenize import word_tokenize

# NLTK 데이터 다운로드
nltk.download('punkt')

# 예시 문장
text = "직장인에게 파이썬은 필수 교육입니다."

# 토큰화
tokens = word_tokenize(text)
print(tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


['직장인에게', '파이썬은', '필수', '교육입니다', '.']


In [2]:
tokens

['직장인에게', '파이썬은', '필수', '교육입니다', '.']

In [ ]:
## 토큰화 (Tokenization)
# 토큰화는 텍스트 데이터를 분석하기 전에 문장을 개별 단어나 문장 단위로 분리하는 과정

In [3]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

# 예시 텍스트
text = "Hello! How are you? I hope you're doing well."

# 단어 토큰화
word_tokens = word_tokenize(text)
print("단어 토큰화:", word_tokens)

# 문장 토큰화
sent_tokens = sent_tokenize(text)
print("문장 토큰화:", sent_tokens)


단어 토큰화: ['Hello', '!', 'How', 'are', 'you', '?', 'I', 'hope', 'you', "'re", 'doing', 'well', '.']
문장 토큰화: ['Hello!', 'How are you?', "I hope you're doing well."]


In [ ]:
# 품사 태깅 (POS Tagging)
# 품사 태깅은 문장에서 각 단어의 품사를 식별하는 과정입니다.

In [ ]:
# 3. 개체명 인식 (Named Entity Recognition, NER)
# 개체명 인식은 텍스트에서 인물, 장소, 조직과 같은 고유명사를 식별하는 작업입니다. NLTK는 개체명 인식을 위한 사전 학습된 모델을 제공합니다.

In [ ]:
# 4. 어간 추출과 표제어 추출 (Stemming and Lemmatization)
# 어간 추출(Stemming)은 단어의 어간(기본 형태)을 찾아내는 작업입니다. 어간 추출은 단어의 변형된 형태를 같은 기본 형태로 변환합니다.
# 표제어 추출(Lemmatization)은 단어의 원형을 찾는 과정으로, 품사 정보를 활용하여 더 정확하게 처리됩니다.

In [ ]:
# 5. 문서 분류 (Document Classification)
# NLTK는 텍스트 데이터를 분류하는 데 사용할 수 있는 도구와 데이터를 제공합니다. 분류 작업은 문서가 긍정적인지, 부정적인지 또는 특정 카테고리에 속하는지를 예측하는 데 사용됩니다.


In [ ]:

# 6. 정서 분석 (Sentiment Analysis)
# NLTK는 텍스트의 정서(긍정, 부정 등)을 분석할 수 있는 도구도 제공합니다. 정서 분석은 리뷰, 소셜 미디어 게시물, 고객 피드백 등의 텍스트 데이터에서 많이 사용됩니다.



In [ ]:
# 파이썬을 활용한 소문자 변환

In [4]:
# 예시 문장
text = "Natural Language Processing is Interesting."

# 소문자 변환
text_lower = text.lower()

# 결과 출력
print(text_lower)


natural language processing is interesting.


In [ ]:
# 파이썬을 활용한 구두점 제거 코드

# 위 코드에서는 정규 표현식을 사용하여 알파벳, 숫자, 공백 이외의 모든 문자를 제거합니다.
# 이 작업을 통해 텍스트에서 불필요한 구두점과 특수 기호가 제거되어 분석의 일관성이 향상됩니다.

In [5]:
import re

# 예시 문장
text = "Hello, world! How's it going?"

# 정규 표현식을 사용한 구두점 제거
text_clean = re.sub(r'[^\w\s]', '', text)

# 결과 출력
print(text_clean)


Hello world Hows it going


In [ ]:
# 불용어(Stopwords) 제거

In [ ]:
# 불용어(Stopwords)는 문장에서 자주 등장하지만 의미 전달에 큰 기여를 하지 않는 단어들입니다.
# 예를 들어, "the", "is", "and" 같은 단어는 문법적으로 중요하지만, 텍스트 분석에서는 큰 의미가 없을 수 있습니다. 이러한 불용어는 분석의 효율성을 높이기 위해 제거하는 것이 일반적입니다.
# 이를 통해 텍스트에서 핵심 정보를 보다 쉽게 추출할 수 있습니다.

In [6]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

# NLTK 데이터 다운로드
nltk.download('punkt')
nltk.download('stopwords')

# 예시 문장
text = "This is a simple sentence."

# 단어 토큰화
tokens = word_tokenize(text)

# 불용어 제거
filtered_tokens = [word for word in tokens if word.lower() not in stopwords.words('english')]

# 결과 출력
print(filtered_tokens)


['simple', 'sentence', '.']


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [ ]:
# (결과)
# 영어 불용어 목록에서 the, is 같은 단어를 제거한 결과입니다.
# 이를 통해 의미 없는 단어들이 제거되고, 텍스트의 핵심 단어만 남게 됩니다.

In [1]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# NLTK에서 제공하는 불용어 목록 로드
nltk.download('stopwords')
nltk.download('punkt')
stop_words = set(stopwords.words('english'))

# 예시 문장
sentence = "This is a simple example sentence for stopword removal."

# 토큰화
words = word_tokenize(sentence)

# 불용어 제거
filtered_sentence = [word for word in words if word.lower() not in stop_words]

# 결과 출력
print("원본 문장:", sentence)
print("불용어 제거 후:", " ".join(filtered_sentence))


원본 문장: This is a simple example sentence for stopword removal.
불용어 제거 후: simple example sentence stopword removal .


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\JYB\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\JYB\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
# 어간 추출(Stemming)은 단어의 접미사나 어형 변화를 제거하여 단어의 기본 형태(어간)를 추출하는 과정입니다.

In [ ]:
# 토큰화란?
# 토큰화(Tokenization)는 자연어 처리(NLP)에서 텍스트를 의미 있는 단위로 나누는 과정을 말합니다. 이 단위를 토큰(Token)이라고 하며, 토큰은 주로 단어 또는 문장 단위로 나뉩니다.
# 토큰화는 자연어 처리의 첫 번째 단계로, 텍스트 데이터를 분석하거나 처리하기 위해 필수적인 전처리 과정입니다.

In [8]:
## 단어 토큰화

In [ ]:
import nltk
from nltk.tokenize import word_tokenize

# 예시 문장
sentence = "고양이가 쥐를 잡았다."

# 단어 토큰화
tokens = word_tokenize(sentence)
print(tokens)


['고양이가', '쥐를', '잡았다', '.']


In [ ]:
# 문장 토큰화

In [ ]:
# 2. 문장 토큰화
# 문장 토큰화(Sentence Tokenization)는 텍스트를 문장 단위로 분리하는 방법입니다.
# 보통 구두점(예: 마침표, 느낌표, 물음표)을 기준으로 문장을 나눕니다.

In [9]:
from nltk.tokenize import sent_tokenize

# 예시 문장
text = "오늘 날씨가 좋다. 우리는 공원에 갈 것이다."

# 문장 토큰화
sentences = sent_tokenize(text)
print(sentences)


['오늘 날씨가 좋다.', '우리는 공원에 갈 것이다.']


# 텍스트 벡터화

In [ ]:
# 텍스트 벡터화는 컴퓨터가 텍스트 데이터를 이해하고 처리할 수 있도록 텍스트를 숫자 형식(벡터)으로 변환하는 과정입니다.
# 자연어는 사람이 이해하기에는 적합하지만, 기계가 처리하기 위해서는 수치 데이터로 변환해야 합니다.
# 텍스트 벡터화는 머신러닝 모델이 텍스트 데이터를 입력으로 받아들일 수 있도록 하는 중요한 전처리 과정입니다.

## Bag of Words (BoW)

In [ ]:
# Bag of Words(BoW)는 텍스트 데이터를 처리하는 대표적인 방법 중 하나로, 문서에서 등장하는 단어들의 빈도를 기반으로 벡터화하는 방식입니다.

### NLTK를 사용한 BoW 구현

In [10]:
import nltk
from nltk.tokenize import word_tokenize
from collections import Counter

# 예제 문장
sentences = ["I love NLP", "NLP is fun", "I love learning"]

# 모든 단어를 저장할 리스트
all_words = []

# 각 문장을 토큰화하여 단어 리스트를 생성
for sentence in sentences:
    words = word_tokenize(sentence.lower())  # 소문자로 변환
    all_words.extend(words)

# 단어 빈도 계산
word_freq = Counter(all_words)

# BoW 출력
print(word_freq)


Counter({'i': 2, 'love': 2, 'nlp': 2, 'is': 1, 'fun': 1, 'learning': 1})


In [ ]:
# 이 코드는 세 문장에서 등장한 단어들의 빈도를 계산한 간단한 BoW 예제입니다.

### Scikit-learn을 사용한 BoW 구현

In [ ]:
# Scikit-learn의 CountVectorizer를 사용하여 텍스트를 BoW로 변환하는 방법

In [ ]:
# 각 문장은 BoW로 변환되어 행렬 형태로 표현됩니다.
# get_feature_names_out()는 단어 사전(모든 고유한 단어)을 보여줍니다.

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

# 예제 문장
sentences = ["I love NLP", "NLP is fun", "I love learning"]

# CountVectorizer 객체 생성
vectorizer = CountVectorizer()

# 문장을 BoW로 변환
X = vectorizer.fit_transform(sentences)

# BoW 출력 (각 문장에 대한 단어 빈도 행렬)
print(X.toarray())

# 단어 사전 출력
print(vectorizer.get_feature_names_out())


[[0 0 0 1 1]
 [1 1 0 0 1]
 [0 0 1 1 0]]
['fun' 'is' 'learning' 'love' 'nlp']


In [ ]:
# [[1 0 1 0 1 0]  # 첫 번째 문장: "I love NLP"
#  [0 1 0 1 0 1]  # 두 번째 문장: "NLP is fun"
#  [1 0 1 1 0 0]] # 세 번째 문장: "I love learning"
# 이 행렬에서 각 행은 문장 하나를 나타내고, 열은 단어 사전에서 각 단어의 출현 빈도를 나타냅니다.
# get_feature_names_out()를 통해 확인한 단어 사전은 ['fun', 'is', 'learning', 'love', 'nlp', 'i']로 구성됩니다.
# 이 사전의 각 단어가 열에 해당합니다.

# 첫 번째 문장 **"I love NLP"**는 i, love, nlp 단어들이 한 번씩 등장하므로, 이 단어들의 위치에 1이 나타납니다.
# 두 번째 문장 **"NLP is fun"**는 is, fun, nlp 단어들이 등장하므로, 해당 단어들의 위치에 1이 표시됩니다.
# 세 번째 문장 **"I love learning"**는 i, love, learning 단어들이 등장하므로, 그 위치에 1이 표시됩니다.
# 이처럼 Scikit-learn의 BoW 구현에서는 각 문장이 단어 사전에 있는 단어들 중에서 몇 번 등장했는지를 벡터로 나타내어, 각 문장에 대한 특징 벡터를 얻을 수 있습니다.

## TF-IDF(Term Frequency-Inverse Document Frequency)

In [ ]:
# TF-IDF(Term Frequency-Inverse Document Frequency)는
# 문서 내 단어의 빈도와, 그 단어가 전체 문서 집합에서 얼마나 자주 등장하는지를 동시에 고려하여 단어의 중요도를 계산하는 방법입니다.


In [ ]:
# Scikit-learn의 TfidfVectorizer를 사용

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 예제 문장
sentences = ["I love NLP", "NLP is fun", "I love learning"]

# TfidfVectorizer 객체 생성
vectorizer = TfidfVectorizer()

# 문장을 TF-IDF로 변환
X = vectorizer.fit_transform(sentences)

# TF-IDF 행렬 출력
print(X.toarray())

# 단어 사전 출력
print(vectorizer.get_feature_names_out())


[[0.         0.         0.         0.70710678 0.70710678]
 [0.62276601 0.62276601 0.         0.         0.4736296 ]
 [0.         0.         0.79596054 0.60534851 0.        ]]
['fun' 'is' 'learning' 'love' 'nlp']


In [ ]:
# 결과:
# TF-IDF 행렬 출력 (각 문장에 대한 단어 빈도 및 가중치):

In [ ]:
# 설명:
# 단어 사전: ['fun', 'is', 'learning', 'love', 'nlp']는 코퍼스에 포함된 모든 고유한 단어들입니다.
# TF-IDF 행렬: 각 행은 문장 하나를 나타내고, 각 열은 단어 사전에서 해당 단어의 TF-IDF 값을 나타냅니다. 이 값은 단어가 문서에서 얼마나 중요한지를 나타내며, 단순 빈도보다 문서 내 의미 있는 단어를 더 잘 나타냅니다.
# 예를 들어, 첫 번째 문장 **"I love NLP"**는 love와 nlp 단어들의 중요도가 높아 그 단어들의 위치에 높은 값이 들어갑니다.

## Word Embedding

In [ ]:

# Word Embedding은 단어를 고차원의 벡터 공간에 매핑하는 방식으로, 단어 간의 의미적 관계를 반영합니다. 대표적인 방법으로 Word2Vec, GloVe, FastText 등이 있습니다.
# 이 방법들은 단어 간의 의미적 유사성을 반영하여, 자연어 처리에서 더욱 효율적으로 텍스트 데이터를 처리할 수 있게 해줍니다

### Word2Vec

In [ ]:
# Word2Vec은 단어의 의미적 유사성을 반영하기 위해, 단어를 밀집 벡터로 학습하는 방법입니다.
# 이 모델은 CBOW (Continuous Bag of Words)와 Skip-gram이라는 두 가지 학습 방식을 통해 단어 간의 관계를 학습합니다.

CBOW (Continuous Bag of Words)

In [ ]:
#  **문맥(context)**을 사용하여 **중심 단어(center word)**를 예측하는 방식입니다.
#     이 모델은 중심 단어 주위의 여러 단어들(문맥)을 기반으로 단어의 의미를 학습합니다.

In [13]:
# 필요 라이브러리 설치
!pip install gensim


In [ ]:
# 코드 설명:
# 입력 데이터: 입력으로 세 개의 간단한 문장이 사용됩니다. 이 문장들은 먼저 word_tokenize로 토큰화됩니다.

# CBOW 모델: Word2Vec의 sg=0 파라미터는 CBOW 방식을 지정합니다. (반면, sg=1이면 Skip-gram 방식입니다). vector_size=50은 각 단어 벡터의 차원을 50으로 설정합니다. window=2는 중심 단어를 예측할 때 양쪽으로 두 개의 단어씩 문맥으로 본다는 뜻입니다.

# 단어 벡터 및 유사도 확인: 학습이 끝나면 'nlp'라는 단어의 벡터를 출력하고, 'nlp'와 유사한 단어들을 출력합니다.

In [14]:
import numpy as np

In [2]:
from gensim.models import Word2Vec
import nltk
from nltk.tokenize import word_tokenize

# 예제 문장들
sentences = ["I love NLP", "NLP is fun", "I love learning"]

# 문장 토큰화
tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]

# CBOW 모델 학습 (Word2Vec의 기본값이 CBOW)
cbow_model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=2, min_count=1, sg=0)

# 'nlp' 단어의 벡터 확인
print("NLP 단어의 벡터:\n", cbow_model.wv['nlp'])

# 가장 유사한 단어 확인
print("NLP와 유사한 단어들:\n", cbow_model.wv.most_similar('nlp'))


NLP 단어의 벡터:
 [-1.0724545e-03  4.7286032e-04  1.0206699e-02  1.8018546e-02
 -1.8605899e-02 -1.4233618e-02  1.2917743e-02  1.7945977e-02
 -1.0030856e-02 -7.5267460e-03  1.4761009e-02 -3.0669451e-03
 -9.0732286e-03  1.3108101e-02 -9.7203208e-03 -3.6320353e-03
  5.7531595e-03  1.9837476e-03 -1.6570430e-02 -1.8897638e-02
  1.4623532e-02  1.0140524e-02  1.3515387e-02  1.5257311e-03
  1.2701779e-02 -6.8107317e-03 -1.8928051e-03  1.1537147e-02
 -1.5043277e-02 -7.8722099e-03 -1.5023164e-02 -1.8600845e-03
  1.9076237e-02 -1.4638334e-02 -4.6675396e-03 -3.8754845e-03
  1.6154870e-02 -1.1861792e-02  9.0322494e-05 -9.5074698e-03
 -1.9207101e-02  1.0014586e-02 -1.7519174e-02 -8.7836506e-03
 -7.0199967e-05 -5.9236528e-04 -1.5322480e-02  1.9229483e-02
  9.9641131e-03  1.8466286e-02]
NLP와 유사한 단어들:
 [('i', 0.1267007291316986), ('love', 0.04237299785017967), ('is', 0.012442132458090782), ('learning', -0.014475276693701744), ('fun', -0.11821283400058746)]


In [ ]:
# 결과:
# 이 코드를 실행하면 NLP 단어의 벡터 값과 NLP와 유사한 단어들이 출력됩니다.
# 이는 모델이 문맥을 학습하여 단어 간의 의미적 유사성을 어떻게 반영하는지 보여줍니다.

Skip-gram

In [ ]:
# 중심 단어를 이용해 주변 단어를 예측하는 방식입니다.
# 이 방식을 통해 단어가 문장에서 사용되는 맥락에 대해 더 깊이 학습할 수 있습니다.

In [ ]:
# 코드 설명:
# 입력 데이터: 입력 문장들을 토큰화한 후 모델에 학습 데이터를 제공합니다.

# Skip-gram 모델 설정: sg=1로 설정하면 Skip-gram 방식으로 학습됩니다. 나머지 파라미터는 CBOW와 동일하게 설정되었지만, Skip-gram은 중심 단어로 주변 단어들을 예측하기 때문에 작은 데이터셋에서 더 효과적일 수 있습니다.

# vector_size=50: 단어 벡터의 차원을 50으로 설정.
# window=2: 중심 단어를 기준으로 양쪽 2개의 단어까지 문맥으로 사용.
# min_count=1: 1번 이상 등장한 단어만 학습에 포함.

In [3]:
from gensim.models import Word2Vec
import nltk
from nltk.tokenize import word_tokenize

# 예제 문장들
sentences = ["I love NLP", "NLP is fun", "I love learning"]

# 문장 토큰화
tokenized_sentences = [word_tokenize(sentence.lower()) for sentence in sentences]

# Skip-gram 모델 학습 (sg=1 설정으로 Skip-gram 방식 사용)
skipgram_model = Word2Vec(sentences=tokenized_sentences, vector_size=50, window=2, min_count=1, sg=1)

# 'nlp' 단어의 벡터 확인
print("NLP 단어의 벡터:\n", skipgram_model.wv['nlp'])

# 가장 유사한 단어 확인
print("NLP와 유사한 단어들:\n", skipgram_model.wv.most_similar('nlp'))


NLP 단어의 벡터:
 [-1.0724545e-03  4.7286032e-04  1.0206699e-02  1.8018546e-02
 -1.8605899e-02 -1.4233618e-02  1.2917743e-02  1.7945977e-02
 -1.0030856e-02 -7.5267460e-03  1.4761009e-02 -3.0669451e-03
 -9.0732286e-03  1.3108101e-02 -9.7203208e-03 -3.6320353e-03
  5.7531595e-03  1.9837476e-03 -1.6570430e-02 -1.8897638e-02
  1.4623532e-02  1.0140524e-02  1.3515387e-02  1.5257311e-03
  1.2701779e-02 -6.8107317e-03 -1.8928051e-03  1.1537147e-02
 -1.5043277e-02 -7.8722099e-03 -1.5023164e-02 -1.8600845e-03
  1.9076237e-02 -1.4638334e-02 -4.6675396e-03 -3.8754845e-03
  1.6154870e-02 -1.1861792e-02  9.0322494e-05 -9.5074698e-03
 -1.9207101e-02  1.0014586e-02 -1.7519174e-02 -8.7836506e-03
 -7.0199967e-05 -5.9236528e-04 -1.5322480e-02  1.9229483e-02
  9.9641131e-03  1.8466286e-02]
NLP와 유사한 단어들:
 [('i', 0.1267007291316986), ('love', 0.04237299785017967), ('is', 0.012442132458090782), ('learning', -0.014475276693701744), ('fun', -0.11821283400058746)]
