# 가우스 소거법 (Gaussian Elimination)

가우스 소거법은 행렬을 행 간의 기본 연산(row operations)을 통해 행 사다리꼴(row echelon form) 또는 축약 행 사다리꼴(reduced row echelon form)로 변환하는 방법이다. 


In [2]:
import numpy as np

def gaussian_elimination_debug(matrix):
    rows, cols = matrix.shape
    for i in range(rows):
        # Print matrix state at each step
        print(f"Step {i + 1}:")
        print(matrix)
        print("\n")
        
        # Make the pivot 1
        pivot = matrix[i, i]
        if pivot != 0:
            matrix[i] = matrix[i] / pivot
        
        # Eliminate elements below the pivot
        for j in range(i + 1, rows):
            multiplier = matrix[j, i]
            matrix[j] = matrix[j] - multiplier * matrix[i]
    
    print("Final Row Echelon Form:")
    print(matrix)
    return matrix

# Example matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 10]
], dtype=float)

row_echelon_form_debug = gaussian_elimination_debug(A.copy())


Step 1:
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]


Step 2:
[[  1.   2.   3.]
 [  0.  -3.  -6.]
 [  0.  -6. -11.]]


Step 3:
[[ 1.  2.  3.]
 [-0.  1.  2.]
 [ 0.  0.  1.]]


Final Row Echelon Form:
[[ 1.  2.  3.]
 [-0.  1.  2.]
 [ 0.  0.  1.]]
