# log

In [ ]:
# 파이썬을 사용하여 로그의 기본 수학적 성질을 구현한 코드입니다. 
# 이 코드는 로그의 정의, 주요 성질(곱셈, 나눗셈, 거듭제곱 법칙)을 보여주며, 이를 간단하게 계산하는 예시

## 로그의 기본 수학적 성질

In [ ]:
# 코드 설명
# 로그 계산 함수:

# log_base(b, x) 함수는 주어진 밑 b에 대한 로그값을 계산합니다.
# math.log(x, b)를 사용하여 밑 b에 대한 로그값을 구할 수 있습니다.
# 곱셈 법칙:

# log_b(m * n)은 log_b(m) + log_b(n)과 같다는 성질을 확인할 수 있습니다.
# 나눗셈 법칙:

# log_b(m / n)은 log_b(m) - log_b(n)과 같다는 성질을 보여줍니다.
# 거듭제곱 법칙:

# log_b(m^k)은 k * log_b(m)과 같다는 것을 계산으로 확인할 수 있습니다.

In [1]:
import math

# 로그 계산 함수 정의
def log_base(b, x):
    return math.log(x, b)

# 기본 로그 예시 (밑이 2인 로그)
b = 2
m = 8
n = 4
k = 3

# 로그 기본 정의
log_m = log_base(b, m)
log_n = log_base(b, n)

print(f"log_{b}({m}) = {log_m}")
print(f"log_{b}({n}) = {log_n}")

# 곱셈 법칙: log_b(m * n) = log_b(m) + log_b(n)
log_mn = log_base(b, m * n)
log_m_plus_log_n = log_m + log_n
print(f"log_{b}({m} * {n}) = {log_mn}")
print(f"log_{b}({m}) + log_{b}({n}) = {log_m_plus_log_n}")

# 나눗셈 법칙: log_b(m / n) = log_b(m) - log_b(n)
log_m_div_n = log_base(b, m / n)
log_m_minus_log_n = log_m - log_n
print(f"log_{b}({m} / {n}) = {log_m_div_n}")
print(f"log_{b}({m}) - log_{b}({n}) = {log_m_minus_log_n}")

# 거듭제곱 법칙: log_b(m^k) = k * log_b(m)
log_m_pow_k = log_base(b, m ** k)
k_times_log_m = k * log_m
print(f"log_{b}({m}^{k}) = {log_m_pow_k}")
print(f"{k} * log_{b}({m}) = {k_times_log_m}")


log_2(8) = 3.0
log_2(4) = 2.0
log_2(8 * 4) = 5.0
log_2(8) + log_2(4) = 5.0
log_2(8 / 4) = 1.0
log_2(8) - log_2(4) = 1.0
log_2(8^3) = 9.0
3 * log_2(8) = 9.0


## 상용로그와 자연로그

In [ ]:
# 상용로그 (Common Logarithm): 밑이 10인 로그를 의미하며, log10 함수로 계산할 수 있습니다.
# 자연로그 (Natural Logarithm): 밑이 e(자연 상수, 약 2.718)를 사용하는 로그로, log 함수로 계산합니다.

In [ ]:
# 상용로그 계산:
# math.log10(x)는 밑 10을 사용하는 상용로그를 계산합니다.
# 예를 들어, log10(100)은 2입니다, 왜냐하면 

# 자연로그 계산:
# math.log(x)는 밑 e(자연 상수)를 사용하는 자연로그를 계산합니다.

# 다양한 값에 대한 로그 계산:
# 값이 1, 10, 20, 50, 100인 경우에 대해 상용로그와 자연로그를 각각 계산하고 출력합니다.

In [2]:
import math

# 상용로그 (밑이 10)
x = 100
common_log = math.log10(x)
print(f"log10({x}) = {common_log}")

# 자연로그 (밑이 e)
natural_log = math.log(x)  # math.log()는 기본적으로 자연로그를 계산
print(f"ln({x}) = {natural_log}")

# 다양한 입력값에 대한 상용로그와 자연로그 계산
values = [1, 10, 20, 50, 100]

print("\n값들에 대한 상용로그와 자연로그 계산:")
for val in values:
    common_log = math.log10(val)
    natural_log = math.log(val)
    print(f"값: {val} -> log10({val}) = {common_log}, ln({val}) = {natural_log}")


log10(100) = 2.0
ln(100) = 4.605170185988092

값들에 대한 상용로그와 자연로그 계산:
값: 1 -> log10(1) = 0.0, ln(1) = 0.0
값: 10 -> log10(10) = 1.0, ln(10) = 2.302585092994046
값: 20 -> log10(20) = 1.3010299956639813, ln(20) = 2.995732273553991
값: 50 -> log10(50) = 1.6989700043360187, ln(50) = 3.912023005428146
값: 100 -> log10(100) = 2.0, ln(100) = 4.605170185988092


In [ ]:
# f는 파이썬의 f-string(formatted string) 기능을 나타냅니다. 
# f-string은 문자열 내에 변수를 쉽게 삽입할 수 있는 파이썬의 문자열 포매팅 방법 중 하나로, 파이썬 3.6부터 도입되었습니다.

# f-string의 사용법
# 문자열 앞에 f를 붙이고, 중괄호 {} 안에 변수를 넣으면, 해당 변수의 값이 문자열에 삽입됩니다.
# 중괄호 {} 안에는 변수뿐만 아니라, 표현식(예: 수식 계산)도 삽입할 수 있습니다.

In [3]:
x = 100
common_log = 2.0

# f-string 사용 예시
print(f"log10({x}) = {common_log}")


log10(100) = 2.0


In [ ]:
# f-string의 장점
# 가독성:

# f-string을 사용하면 문자열 안에 변수를 바로 삽입할 수 있기 때문에 코드가 더 간결하고 읽기 쉬워집니다.
# 표현식 사용 가능:

# 중괄호 {} 안에 간단한 표현식을 넣어 계산 결과를 출력할 수 있습니다.

# 벡터

In [ ]:
# 벡터의 사칙연산(덧셈, 뺄셈, 곱셈, 나눗셈)과 **Norm(벡터의 크기)**을 계산하는 코드입니다. 
# 이를 위해 NumPy 라이브러리를 사용

## 벡터 사칙연산(벡터 덧셈, 뺄셈, 원소별 곱셈, 나눗셈)

In [ ]:
# 덧셈: 각 벡터의 원소끼리 더해집니다.
# 뺄셈: 각 벡터의 원소끼리 빼집니다.
# 원소별 곱셈: 각 벡터의 대응하는 원소끼리 곱합니다.
# 원소별 나눗셈: 각 벡터의 대응하는 원소끼리 나눕니다

In [4]:
import numpy as np

# 두 개의 벡터 정의
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

In [5]:
# 벡터 덧셈
vector_add = vector_a + vector_b
print(f"벡터 덧셈: {vector_add}")

# 벡터 뺄셈
vector_sub = vector_a - vector_b
print(f"벡터 뺄셈: {vector_sub}")

# 벡터 원소별 곱셈
vector_mul = vector_a * vector_b
print(f"벡터 원소별 곱셈: {vector_mul}")

# 벡터 원소별 나눗셈
vector_div = vector_a / vector_b
print(f"벡터 원소별 나눗셈: {vector_div}")


벡터 덧셈: [5 7 9]
벡터 뺄셈: [-3 -3 -3]
벡터 원소별 곱셈: [ 4 10 18]
벡터 원소별 나눗셈: [0.25 0.4  0.5 ]


## 벡터의 내적(Dot Product)

In [ ]:
# 벡터 내적(Dot Product) 공식
# 두 벡터 𝑎와 𝑏가 있을 때, 벡터 내적은 다음과 같이 계산됩니다:
# 𝑎⋅𝑏=𝑎1⋅𝑏1+𝑎2⋅𝑏2+⋯+𝑎𝑛⋅𝑏𝑛
# 즉, 각 대응하는 원소들을 곱하고, 그 값을 모두 더한 결과가 내적입니다.


In [ ]:
# np.dot(a, b): NumPy에서 제공하는 dot 함수는 두 벡터 또는 행렬의 내적을 계산하는 함수입니다.
# 벡터 내적 결과는 두 벡터의 크기와 방향에 따라 하나의 숫자(스칼라)로 나타납니다.

In [7]:
import numpy as np

# 두 개의 벡터 정의
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# 벡터 내적 계산
dot_product = np.dot(vector_a, vector_b)

# 결과 출력
print(f"벡터 a: {vector_a}")
print(f"벡터 b: {vector_b}")
print(f"벡터 a와 b의 내적: {dot_product}")


벡터 a: [1 2 3]
벡터 b: [4 5 6]
벡터 a와 b의 내적: 32


다차원 벡터 예시

In [ ]:
# 만약 벡터가 더 큰 차원을 가진다면, 동일한 방식으로 내적을 계산할 수 있습니다. 
# 예를 들어, 4차원 벡터에 대해서도 동일하게 작동합니다.

In [8]:
vector_c = np.array([1, 2, 3, 4])
vector_d = np.array([5, 6, 7, 8])

dot_product_cd = np.dot(vector_c, vector_d)
print(f"벡터 c와 d의 내적: {dot_product_cd}")


벡터 c와 d의 내적: 70


## 벡터 Norm (벡터의 크기)

In [ ]:
# 벡터의 Norm(벡터의 크기)는 벡터의 길이를 나타냅니다. 
# Norm은 여러 종류가 있으며, 가장 일반적인 것은 L2 Norm(유클리드 거리)입니다.

In [6]:
# L2 Norm (유클리드 노름)
l2_norm = np.linalg.norm(vector_a)
print(f"벡터 a의 L2 Norm (유클리드 노름): {l2_norm}")

# L1 Norm (맨하탄 노름)
l1_norm = np.linalg.norm(vector_a, ord=1)
print(f"벡터 a의 L1 Norm (맨하탄 노름): {l1_norm}")

# 무한 Norm (최대 절댓값)
inf_norm = np.linalg.norm(vector_a, ord=np.inf)
print(f"벡터 a의 무한 Norm (최대 절댓값): {inf_norm}")


벡터 a의 L2 Norm (유클리드 노름): 3.7416573867739413
벡터 a의 L1 Norm (맨하탄 노름): 6.0
벡터 a의 무한 Norm (최대 절댓값): 3.0


# 행렬

## 행렬 덧셈, 뺄셈, 원소별 곱셈, 원소별 나눗셈

In [ ]:
# 행렬의 사칙연산(덧셈, 뺄셈, 곱셈, 나눗셈)을 구현하기 위해 NumPy 라이브러리를 사용할 수 있습니다

In [ ]:
# 행렬 덧셈, 뺄셈, 원소별 곱셈, 나눗셈은 각 대응하는 원소끼리 연산이 이루어집니다.
# **행렬 곱셈(점곱)**은 수학적으로 정의된 방식으로, 첫 번째 행렬의 행과 두 번째 행렬의 열을 곱하고 더하는 방식으로 계산됩니다.

In [9]:
import numpy as np

# 두 개의 행렬 정의
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8, 9], [10, 11, 12]])

# 행렬 덧셈
matrix_add = matrix_a + matrix_b
print(f"행렬 덧셈:\n{matrix_add}")

# 행렬 뺄셈
matrix_sub = matrix_a - matrix_b
print(f"행렬 뺄셈:\n{matrix_sub}")

# 행렬 원소별 곱셈
matrix_mul = matrix_a * matrix_b
print(f"행렬 원소별 곱셈:\n{matrix_mul}")

# 행렬 원소별 나눗셈
matrix_div = matrix_a / matrix_b
print(f"행렬 원소별 나눗셈:\n{matrix_div}")


행렬 덧셈:
[[ 8 10 12]
 [14 16 18]]
행렬 뺄셈:
[[-6 -6 -6]
 [-6 -6 -6]]
행렬 원소별 곱셈:
[[ 7 16 27]
 [40 55 72]]
행렬 원소별 나눗셈:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [10]:
# 행렬 곱셈 (점곱)
matrix_dot = np.dot(matrix_a, matrix_b.T)  # 두 번째 행렬은 전치하여 곱셈 가능
print(f"행렬 점곱 (수학적 곱셈):\n{matrix_dot}")


행렬 점곱 (수학적 곱셈):
[[ 50  68]
 [122 167]]


In [ ]:
# 행렬 곱셈은 첫 번째 행렬의 행과 두 번째 행렬의 열을 곱하고 더해서 계산됩니다. 
# 여기서는 matrix_b.T로 전치 행렬을 사용하여 곱셈이 가능하도록 했습니다.

## 행렬의 역행렬(inverse matrix)

In [ ]:
# 역행렬은 정사각 행렬에 대해서만 존재하며, 행렬 𝐴의 역행렬 𝐴−1 는 다음과 같은 관계를 만족합니다:
# 𝐴⋅𝐴−1=𝐼


In [ ]:
# NumPy에서는 np.linalg.inv() 함수를 사용하여 행렬의 역행렬을 구할 수 있습니다.

In [11]:
import numpy as np

# 2x2 정사각 행렬 정의
matrix = np.array([[4, 7], [2, 6]])

# 행렬의 역행렬 계산
inverse_matrix = np.linalg.inv(matrix)

# 결과 출력
print("원본 행렬:")
print(matrix)

print("\n역행렬:")
print(inverse_matrix)

# 행렬과 역행렬을 곱하여 단위 행렬이 되는지 확인
identity_matrix = np.dot(matrix, inverse_matrix)
print("\n원본 행렬과 역행렬의 곱:")
print(identity_matrix)


원본 행렬:
[[4 7]
 [2 6]]

역행렬:
[[ 0.6 -0.7]
 [-0.2  0.4]]

원본 행렬과 역행렬의 곱:
[[ 1.00000000e+00 -1.11022302e-16]
 [-1.11022302e-16  1.00000000e+00]]


## 행렬의 전치(Transpose of a matrix)

In [ ]:
# 행렬의 전치(Transpose of a matrix)를 계산하려면 NumPy 라이브러리를 사용할 수 있습니다.
# 전치행렬은 원래 행렬의 행과 열을 서로 바꾸는 연산입니다.

# NumPy에서는 np.transpose() 함수나 .T 속성을 사용하여 행렬의 전치를 쉽게 계산할 수 있습니다.

In [12]:
import numpy as np

# 원본 행렬 정의
matrix = np.array([[1, 2, 3], [4, 5, 6]])

# 전치행렬 계산
transpose_matrix = np.transpose(matrix)

# 결과 출력
print("원본 행렬:")
print(matrix)

print("\n전치 행렬:")
print(transpose_matrix)


원본 행렬:
[[1 2 3]
 [4 5 6]]

전치 행렬:
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# 다른 방법으로 전치 계산
# NumPy에서는 전치행렬을 계산하는 여러 방법이 있습니다:

# np.transpose(matrix):

# np.transpose() 함수를 사용하여 전치행렬을 계산합니다.
# matrix.T:

# NumPy 배열 객체 자체에 포함된 .T 속성을 사용하여 전치행렬을 간단히 얻을 수 있습니다.

In [13]:
# 전치 행렬 다른 방식
transpose_matrix_alt = matrix.T
print("전치 행렬 (matrix.T):")
print(transpose_matrix_alt)


전치 행렬 (matrix.T):
[[1 4]
 [2 5]
 [3 6]]


# 미분

## 미분, 편미분, 전미분

In [ ]:
# SymPy 라이브러리를 사용하면 미분, 편미분, 그리고 전미분을 쉽게 계산할 수 있습니다.

# 미분은 주어진 함수의 변화율을 구하고, 
# 편미분은 다변수 함수에서 특정 변수에 대한 변화율을 구합니다. 
# 전미분은 여러 변수의 미분을 합친 결과를 나타냅니다.

In [16]:
import sympy as sp

# 변수 정의
x, y = sp.symbols('x y')

# 함수 정의
f = x**2 + 3*x + 5

# 1. 미분 (f'(x))
f_prime = sp.diff(f, x)
print(f"함수 f(x)의 미분: {f_prime}")

# 2. 편미분 (g(x, y) = x^2 * y + 3xy^2 + 5에 대한 x와 y 편미분)
g = x**2 * y + 3*x*y**2 + 5

# g(x, y)에 대한 x에 대한 편미분
g_partial_x = sp.diff(g, x)
print(f"함수 g(x, y)의 x에 대한 편미분: {g_partial_x}")

# g(x, y)에 대한 y에 대한 편미분
g_partial_y = sp.diff(g, y)
print(f"함수 g(x, y)의 y에 대한 편미분: {g_partial_y}")

# 3. 전미분 (Total Derivative of f(x, y))
# f(x, y) = x^2 + y^2 + 2xy 라는 함수가 있을 때
f_total = x**2 + y**2 + 2*x*y

# x와 y 모두에 대해 전미분을 계산
df_dx = sp.diff(f_total, x)
df_dy = sp.diff(f_total, y)

# 전미분 (dx, dy 포함)
df = df_dx + df_dy
print(f"함수 f(x, y)의 전미분: {df}")


함수 f(x)의 미분: 2*x + 3
함수 g(x, y)의 x에 대한 편미분: 2*x*y + 3*y**2
함수 g(x, y)의 y에 대한 편미분: x**2 + 6*x*y
함수 f(x, y)의 전미분: 4*x + 4*y


In [ ]:
# 미분: 함수 f(x) = x^2 + 3x + 5에 대해 x에 대한 미분을 계산한 결과는 2*x + 3입니다.

# 편미분: 함수 g(x, y) = x^2 * y + 3xy^2 + 5에 대해 각각의 변수 x와 y에 대한 편미분을 계산한 결과입니다.

# g를 x에 대해 편미분한 결과는 2*x*y + 3*y^2입니다.
# g를 y에 대해 편미분한 결과는 x^2 + 6*x*y입니다.
# 전미분: 함수 f(x, y) = x^2 + y^2 + 2xy에 대해 x와 y에 대한 각각의 미분을 더한 결과는 4*x + 4*y입니다. 이는 전미분의 결과입니다.

## 행렬 미분(Matrix Differentiation)

In [ ]:
# 행렬 미분(Matrix Differentiation)**을 계산하는 예시를 SymPy 라이브러리를 사용하여 보여드릴 수 있습니다. 
# 행렬 미분은 주로 벡터와 행렬을 다루는 최적화 문제에서 사용되며, 행렬의 각 요소에 대해 미분을 계산합니다.

In [ ]:
# 주어진 함수:𝑓(𝑥)=𝑥𝑇𝐴𝑥이 함수에 대해 𝑥에 대해 미분을 구할 것입니다.

In [17]:
import sympy as sp

# 벡터와 행렬 정의
x1, x2 = sp.symbols('x1 x2')  # 벡터 x의 원소
A = sp.Matrix([[2, 1], [1, 3]])  # 2x2 행렬 A
x = sp.Matrix([x1, x2])  # 벡터 x

# 함수 정의: f(x) = x^T A x
f = x.T * A * x

# f에 대한 벡터 x의 미분 계산 (그라디언트)
df_dx = sp.Matrix([sp.diff(f, xi) for xi in x])

# 결과 출력
print("함수 f(x) = x^T A x:")
sp.pprint(f)

print("\n벡터 x에 대한 미분 (그라디언트):")
sp.pprint(df_dx)


함수 f(x) = x^T A x:
[x₁⋅(2⋅x₁ + x₂) + x₂⋅(x₁ + 3⋅x₂)]

벡터 x에 대한 미분 (그라디언트):
⎡4⋅x₁ + 2⋅x₂⎤
⎢           ⎥
⎣2⋅x₁ + 6⋅x₂⎦


In [ ]:
# 행렬과 벡터 정의:벡터 𝑥는 x1, x2로 정의되었고, 행렬 𝐴는 2x2 행렬로 정의됩니다.
# 함수 𝑓(𝑥)는 벡터의 전치행렬과 행렬 𝐴, 그리고 벡터의 곱으로 구성됩니다.
# 미분 (그라디언트):함수 𝑓(𝑥)를 벡터 𝑥에 대해 미분하면 그라디언트(Gradient)를 구할 수 있습니다. 
#     이 그라디언트는 𝑥가 변화할 때 함수 𝑓(𝑥)의 변화율을 나타냅니다.
# 결과는 각 변수에 대한 미분으로 구성된 벡터입니다:
# ∇𝑓

# 응용 예시
# 행렬 미분은 기계 학습에서 자주 사용되며, 
# 특히 **행렬 방정식에서 경사 하강법(Gradient Descent)**을 사용할 때 유용합니다.
# 이러한 그라디언트를 이용해 손실 함수의 최소값을 찾는 데 사용됩니다.

# 경사하강법

# 교차 엔트로피