전치행렬(Transpose Matrix)은 행렬의 행(row)과 열(column)을 서로 바꾼 행렬이다.
즉, 행 → 열 ,  열 → 행으로 뒤바뀐 행렬을 의미한다.

### 두 번 전치하면 원래 행렬로 돌아옴

In [2]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

print((A.T).T)


[[1 2]
 [3 4]]


### 합의 전치 = 전치의 합

In [3]:
B = np.array([[5, 6],
              [7, 8]])

left = (A + B).T
right = A.T + B.T

print(left)
print(right)


[[ 6 10]
 [ 8 12]]
[[ 6 10]
 [ 8 12]]


### 곱의 전치 = 순서를 바꾼 전치의 곱

In [4]:
left = (A @ B).T
right = B.T @ A.T

print(left)
print(right)


[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


### 스칼라 배의 전치

In [5]:
c = 3
left = (c * A).T
right = c * A.T

print(left)
print(right)


[[ 3  9]
 [ 6 12]]
[[ 3  9]
 [ 6 12]]


### 내적(dot product) 표현

In [1]:
import numpy as np

x = np.array([1, 3, -2])
y = np.array([4, -1, 5])

dot1 = np.dot(x, y)
dot2 = x.T @ y   # @는 행렬곱 기호

print(dot1, dot2)

-9 -9
