# https://www.tensorflow.org/

In [ ]:
# TensorFlow에는 다양한 튜토리얼이 제공되어 있으며, 이를 통해 기초부터 고급까지 다양한 딥러닝 개념을 실습할 수 있습니다. 

1. TensorFlow 공식 튜토리얼
TensorFlow 공식 튜토리얼은 TensorFlow Tutorials에서 확인할 수 있습니다. 이 튜토리얼에는 기초적인 머신러닝부터 고급 모델까지 다양한 내용이 포함되어 있습니다.

주요 튜토리얼 카테고리
기초(Basics): TensorFlow와 Keras의 기본 개념을 다룹니다.

Hello, TensorFlow: 간단한 예제와 텐서의 기본 사용법.
데이터셋 로딩 및 전처리: tf.data를 사용하여 데이터를 효율적으로 처리하는 방법.
자동 미분 및 그라디언트 계산: tf.GradientTape를 활용해 모델을 학습하는 기본 개념.
텍스트 분류(Text Classification): 텍스트 데이터를 분류하는 모델을 만드는 방법.

예: IMDb 영화 리뷰 감성 분석, SMS 메시지 분류 등.
이미지 분류(Image Classification): 이미지 데이터셋을 사용한 분류 모델 생성.

예: MNIST 손글씨 숫자 데이터셋 분류, CIFAR-10 분류 등.
시계열(Time Series): 시계열 예측을 위한 RNN 모델을 다루는 튜토리얼.

예: 기온 데이터 예측, 주가 데이터 예측 등.
강화 학습(Reinforcement Learning): 기본적인 강화 학습 개념을 소개하고 다양한 예제를 제공합니다.

예: CartPole, DQN(Deep Q-Network) 튜토리얼 등.
생성 모델(Generative Models): GAN(Generative Adversarial Networks)과 VAE(Variational Autoencoder)와 같은 생성 모델에 대한 튜토리얼.

전이 학습(Transfer Learning): 사전 학습된 모델을 사용하는 전이 학습 기법을 소개합니다.

예: MobileNet을 사용한 이미지 분류, EfficientNet 튜토리얼 등.

# 기본 학습 과정 이해

##  TensorFlow 설치 및 임포트

In [ ]:
pip install tensorflow


In [27]:
import tensorflow as tf


## 데이터 준비

In [ ]:
# 모델을 학습할 데이터를 준비합니다. 
# 예제에서는 X와 y가 주어진 간단한 데이터셋을 사용합니다.

In [ ]:
#  코드는 X와 y 간의 관계가 y = 2 * X인 데이터에서 학습합니다.
# Dense 레이어를 사용한 단순한 선형 모델이 y = 2 * X의 관계를 학습하게 됩니다.
# fit을 통해 데이터를 학습하고, predict를 통해 새로운 입력 값에 대한 예측을 수행합니다.

In [ ]:
# 상수 텐서를 생성 :  tf.constant

# tf.constant:
# tf.constant는 고정된 값(변하지 않는 값)을 가지는 텐서를 생성합니다.
# 여기서는 [[1], [2], [3], [4]]라는 2차원 배열 형태의 데이터를 사용하여 텐서를 정의하고 있습니다.

# 데이터 구조:
# [[1], [2], [3], [4]]는 X 텐서의 값을 나타내며, (4, 1) 모양의 2차원 텐서입니다.
# 각 값이 [1], [2], [3], [4]로 세로로 배열된 형태입니다. 즉, 4개의 행과 1개의 열로 구성된 텐서입니다.

# dtype=tf.float32
# dtype=tf.float32는 생성되는 텐서의 데이터 유형을 float32로 설정합니다. 이는 부동소수점 32비트 형식을 사용함을 의미합니다.
# 텐서의 각 요소가 float32 형식의 실수로 저장됩니다. 
# 딥러닝 모델 학습에서 부동소수점 데이터가 일반적으로 사용되기 때문에 float32를 자주 설정합니다.

In [ ]:
# 텐서(Tensor) 생성 및 조작
# TensorFlow에서 모든 데이터는 텐서 형태로 표현됩니다. 
# 텐서는 다차원 배열로, 파이썬의 리스트와 Numpy 배열과 유사합니다.

In [28]:
X = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)  # 입력 데이터
y = tf.constant([[2], [4], [6], [8]], dtype=tf.float32)  # 정답 데이터


In [30]:
X

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[1.],
       [2.],
       [3.],
       [4.]], dtype=float32)>

In [31]:
y

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[2.],
       [4.],
       [6.],
       [8.]], dtype=float32)>

## 모델 정의

In [6]:
# TensorFlow에서는 모델을 정의할 때 tf.keras.Sequential을 자주 사용합니다. 
# Sequential 모델은 레이어를 순차적으로 쌓아서 정의할 수 있습니다.

In [7]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])  # 출력 뉴런 1개, 입력 형태는 1차원 데이터
])


## 모델 컴파일

In [ ]:
#모델을 학습하기 전에 손실 함수와 최적화 알고리즘을 설정해야 합니다.

In [ ]:
# optimizer: 경사하강법을 사용할 경우 'sgd' (Stochastic Gradient Descent)을 설정합니다.
# loss: 예제에서는 평균 제곱 오차(MSE: mean_squared_error)를 손실 함수로 설정했습니다.

In [8]:
model.compile(optimizer='sgd', loss='mean_squared_error')


## 모델 학습

In [ ]:
# fit 함수를 사용하여 모델을 학습시킵니다.

In [ ]:
# X, y는 학습 데이터, epochs는 학습 반복 횟수입니다. 
# 에포크가 클수록 모델이 데이터를 더 많이 학습합니다.

In [9]:
model.fit(X, y, epochs=1000)


Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step - loss: 31.0254
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 21.5472
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 14.9703
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 10.4066
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 7.2398
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 5.0424
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 3.5175
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 2.4593
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 1.7249
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1.2153
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.8615
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.6159
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.4454
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.3270
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.2447

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0395
Epoch 83/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0393
Epoch 84/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0390
Epoch 85/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0388
Epoch 86/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0386
Epoch 87/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0383
Epoch 88/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0381
Epoch 89/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0379
Epoch 90/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0377
Epoch 91/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0374
Epoch 92/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0372
Epoch 93/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0370
Epoch 94/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.0368
Epoch 95/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0365
Epoch 96/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.0363
Epoch 97/

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0245
Epoch 163/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0243
Epoch 164/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0242
Epoch 165/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0240
Epoch 166/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0239
Epoch 167/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0237
Epoch 168/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0236
Epoch 169/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0234
Epoch 170/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0233
Epoch 171/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0232
Epoch 172/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0230
Epoch 173/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0229
Epoch 174/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0228
Epoch 175/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0226
Epoch 176/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0151
Epoch 243/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0150
Epoch 244/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0150
Epoch 245/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0149
Epoch 246/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0148
Epoch 247/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0147
Epoch 248/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0146
Epoch 249/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0145
Epoch 250/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0144
Epoch 251/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0143
Epoch 252/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0143
Epoch 253/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0142
Epoch 254/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0141
Epoch 255/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0140
Epoch 256/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0094
Epoch 323/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0093
Epoch 324/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0093
Epoch 325/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.0092
Epoch 326/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0091
Epoch 327/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0091
Epoch 328/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0090
Epoch 329/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.0090
Epoch 330/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0089
Epoch 331/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0089
Epoch 332/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0088
Epoch 333/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.0088
Epoch 334/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0087
Epoch 335/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0087
Epoch 336/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.0058
Epoch 403/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.0058
Epoch 404/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.0057
Epoch 405/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0057
Epoch 406/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0057
Epoch 407/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0056
Epoch 408/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0056
Epoch 409/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.0056
Epoch 410/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0055
Epoch 411/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.0055
Epoch 412/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.0055
Epoch 413/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 0.0054
Epoch 414/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.0054
Epoch 415/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.0054
Epoch 416/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.0036
Epoch 483/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0036
Epoch 484/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.0035
Epoch 485/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0035
Epoch 486/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0035
Epoch 487/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0035
Epoch 488/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0035
Epoch 489/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.0034
Epoch 490/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0034
Epoch 491/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0034
Epoch 492/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0034
Epoch 493/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0034
Epoch 494/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0033
Epoch 495/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0033
Epoch 496/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0022
Epoch 563/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.0022
Epoch 564/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.0022
Epoch 565/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0022
Epoch 566/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.0022
Epoch 567/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0022
Epoch 568/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0021
Epoch 569/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.0021
Epoch 570/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0021
Epoch 571/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0021
Epoch 572/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.0021
Epoch 573/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0021
Epoch 574/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.0021
Epoch 575/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0021
Epoch 576/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0014
Epoch 643/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.0014
Epoch 644/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0014
Epoch 645/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.0014
Epoch 646/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0013
Epoch 647/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.0013
Epoch 648/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0013
Epoch 649/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.0013
Epoch 650/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.0013
Epoch 651/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.0013
Epoch 652/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0013
Epoch 653/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0013
Epoch 654/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.0013
Epoch 655/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.0013
Epoch 656/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 8.5595e-04
Epoch 722/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 8.5083e-04
Epoch 723/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 8.4574e-04
Epoch 724/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 8.4068e-04
Epoch 725/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 8.3566e-04
Epoch 726/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.3066e-04
Epoch 727/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 8.2570e-04
Epoch 728/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 8.2076e-04
Epoch 729/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.1585e-04
Epoch 730/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 8.1097e-04
Epoch 731/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 8.0613e-04
Epoch 732/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.0131e-04
Epoch 733/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 7.9652e-04
Epoch 734/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 7.9175e-04
Epoch 7

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 5.3940e-04
Epoch 799/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 5.3617e-04
Epoch 800/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 5.3297e-04
Epoch 801/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5.2978e-04
Epoch 802/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5.2661e-04
Epoch 803/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 5.2346e-04
Epoch 804/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 5.2033e-04
Epoch 805/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 5.1722e-04
Epoch 806/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 5.1413e-04
Epoch 807/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 5.1106e-04
Epoch 808/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 5.0800e-04
Epoch 809/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 5.0497e-04
Epoch 810/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 5.0194e-04
Epoch 811/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 4.9894e-04
Epoch 8

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 3.3992e-04
Epoch 876/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 3.3789e-04
Epoch 877/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 3.3586e-04
Epoch 878/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 3.3386e-04
Epoch 879/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 3.3186e-04
Epoch 880/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 3.2988e-04
Epoch 881/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 3.2791e-04
Epoch 882/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 3.2594e-04
Epoch 883/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 3.2399e-04
Epoch 884/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 3.2206e-04
Epoch 885/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 3.2013e-04
Epoch 886/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 3.1822e-04
Epoch 887/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 3.1632e-04
Epoch 888/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 3.1443e-04
Epoch 8

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 2.1421e-04
Epoch 953/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2.1293e-04
Epoch 954/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 2.1165e-04
Epoch 955/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 2.1039e-04
Epoch 956/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 2.0913e-04
Epoch 957/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 2.0788e-04
Epoch 958/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 2.0664e-04
Epoch 959/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 2.0540e-04
Epoch 960/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 2.0417e-04
Epoch 961/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2.0296e-04
Epoch 962/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 2.0174e-04
Epoch 963/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 2.0054e-04
Epoch 964/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1.9933e-04
Epoch 965/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1.9814e-04
Epoch 9

## 모델 평가

In [ ]:
# 학습이 완료된 모델의 성능을 평가하거나 예측을 수행할 수 있습니다.

In [ ]:
# test_input은 모델에 입력할 값으로, 여기서는 5를 사용합니다.
# tf.constant([[5]], dtype=tf.float32)를 통해 TensorFlow 텐서를 생성했습니다. 
# tf.constant는 고정된 상수 값을 가지는 텐서를 정의하며, 여기서는 5라는 값을 float32 타입으로 생성했습니다.
# 이 입력 텐서의 모양은 [[5]]로, 2차원 배열 형식입니다. 이는 모델의 입력 형식에 맞추기 위해 사용합니다.

# 모델 예측 수행:
# prediction = model.predict(test_input)
# model.predict(test_input)은 학습된 model을 사용해 test_input에 대한 예측을 수행합니다.
# model.predict 함수는 입력 텐서를 받아, 학습된 모델 파라미터에 따라 해당 값의 출력을 계산합니다.
# 예측 결과는 prediction 변수에 저장됩니다. 이 값은 입력값 5에 대응하는 모델의 출력입니다.

In [10]:
test_input = tf.constant([[5]], dtype=tf.float32)  # 새 입력 값
prediction = model.predict(test_input)  # 예측 수행
print("Prediction for input 5:", prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
Prediction for input 5: [[9.978338]]


## 학습된 가중치 확인

In [ ]:
# 학습 후에는 모델의 가중치와 편향을 확인할 수 있습니다.

In [11]:
weights, biases = model.layers[0].get_weights()
print("Weights:", weights)
print("Biases:", biases)


Weights: [[1.9894836]]
Biases: [0.03091979]


코드 종합

In [ ]:
import tensorflow as tf

# 데이터 정의
X = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)  # 입력 데이터
y = tf.constant([[2], [4], [6], [8]], dtype=tf.float32)  # 정답 데이터

# 모델 정의
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])  # 출력 뉴런 1개, 입력 형태는 1차원 데이터
])

# 모델 컴파일
model.compile(optimizer='sgd', loss='mean_squared_error')

# 모델 학습
model.fit(X, y, epochs=1000)

# 예측 수행
test_input = tf.constant([[5]], dtype=tf.float32)
prediction = model.predict(test_input)
print("Prediction for input 5:", prediction)

# 학습된 가중치와 편향 확인
weights, biases = model.layers[0].get_weights()
print("Weights:", weights)
print("Biases:", biases)


데이터 변경

In [12]:
import tensorflow as tf

# 데이터 정의
X = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)  # 입력 데이터
y = tf.constant([[2], [4], [6], [10]], dtype=tf.float32)  # 정답 데이터

# 모델 정의
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])  # 출력 뉴런 1개, 입력 형태는 1차원 데이터
])

# 모델 컴파일
model.compile(optimizer='sgd', loss='mean_squared_error')

# 모델 학습
model.fit(X, y, epochs=1000)

# 예측 수행
test_input = tf.constant([[5]], dtype=tf.float32)
prediction = model.predict(test_input)
print("Prediction for input 5:", prediction)

# 학습된 가중치와 편향 확인
weights, biases = model.layers[0].get_weights()
print("Weights:", weights)
print("Biases:", biases)


Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 270ms/step - loss: 71.3649
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 49.7981
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 34.8323
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 24.4467
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 17.2393
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 12.2371
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.7651
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 6.3549
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 4.6813
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 3.5191
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 2.7115
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2.1501
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1.7595
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - loss: 1.4874
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 1.29

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.6848
Epoch 83/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.6825
Epoch 84/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.6802
Epoch 85/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.6780
Epoch 86/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.6757
Epoch 87/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.6735
Epoch 88/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.6712
Epoch 89/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.6690
Epoch 90/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.6668
Epoch 91/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.6646
Epoch 92/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.6624
Epoch 93/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.6603
Epoch 94/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.6581
Epoch 95/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.6560
Epoch 96/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.6538
Epoch 97/

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.5382
Epoch 163/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.5368
Epoch 164/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.5353
Epoch 165/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.5339
Epoch 166/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.5325
Epoch 167/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.5311
Epoch 168/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.5298
Epoch 169/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.5284
Epoch 170/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.5270
Epoch 171/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.5257
Epoch 172/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.5243
Epoch 173/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.5230
Epoch 174/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.5216
Epoch 175/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.5203
Epoch 176/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.4474
Epoch 243/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.4465
Epoch 244/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.4457
Epoch 245/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.4448
Epoch 246/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.4439
Epoch 247/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.4431
Epoch 248/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.4422
Epoch 249/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.4414
Epoch 250/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.4405
Epoch 251/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.4397
Epoch 252/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.4388
Epoch 253/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.4380
Epoch 254/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.4372
Epoch 255/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.4364
Epoch 256/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3912
Epoch 323/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3907
Epoch 324/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3902
Epoch 325/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3896
Epoch 326/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3891
Epoch 327/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3886
Epoch 328/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3880
Epoch 329/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3875
Epoch 330/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3870
Epoch 331/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3865
Epoch 332/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3859
Epoch 333/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3854
Epoch 334/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.3849
Epoch 335/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3844
Epoch 336/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.3565
Epoch 403/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3561
Epoch 404/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.3558
Epoch 405/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.3555
Epoch 406/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.3551
Epoch 407/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3548
Epoch 408/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 0.3545
Epoch 409/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3542
Epoch 410/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3538
Epoch 411/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3535
Epoch 412/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3532
Epoch 413/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3529
Epoch 414/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3526
Epoch 415/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3522
Epoch 416/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3350
Epoch 483/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3347
Epoch 484/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3345
Epoch 485/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.3343
Epoch 486/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3341
Epoch 487/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.3339
Epoch 488/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3337
Epoch 489/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.3335
Epoch 490/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3333
Epoch 491/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3331
Epoch 492/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3329
Epoch 493/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3327
Epoch 494/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3325
Epoch 495/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3323
Epoch 496/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3216
Epoch 563/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3215
Epoch 564/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3214
Epoch 565/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3212
Epoch 566/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3211
Epoch 567/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3210
Epoch 568/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3209
Epoch 569/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3207
Epoch 570/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3206
Epoch 571/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3205
Epoch 572/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3204
Epoch 573/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3203
Epoch 574/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3201
Epoch 575/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3200
Epoch 576/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3134
Epoch 643/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.3133
Epoch 644/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 0.3132
Epoch 645/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3132
Epoch 646/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.3131
Epoch 647/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3130
Epoch 648/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3129
Epoch 649/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3128
Epoch 650/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.3128
Epoch 651/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3127
Epoch 652/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3126
Epoch 653/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3125
Epoch 654/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3125
Epoch 655/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - loss: 0.3124
Epoch 656/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3083
Epoch 723/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3082
Epoch 724/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3082
Epoch 725/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 0.3081
Epoch 726/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3081
Epoch 727/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.3080
Epoch 728/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.3080
Epoch 729/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3079
Epoch 730/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3079
Epoch 731/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3079
Epoch 732/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3078
Epoch 733/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.3078
Epoch 734/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.3077
Epoch 735/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3077
Epoch 736/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3051
Epoch 803/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.3051
Epoch 804/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.3051
Epoch 805/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3050
Epoch 806/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.3050
Epoch 807/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3050
Epoch 808/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.3049
Epoch 809/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3049
Epoch 810/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3049
Epoch 811/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3049
Epoch 812/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3048
Epoch 813/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3048
Epoch 814/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3048
Epoch 815/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3047
Epoch 816/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3032
Epoch 883/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3032
Epoch 884/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3031
Epoch 885/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3031
Epoch 886/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3031
Epoch 887/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3031
Epoch 888/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3031
Epoch 889/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3030
Epoch 890/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3030
Epoch 891/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.3030
Epoch 892/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.3030
Epoch 893/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3030
Epoch 894/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3030
Epoch 895/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.3029
Epoch 896/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3020
Epoch 963/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3020
Epoch 964/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3019
Epoch 965/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3019
Epoch 966/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.3019
Epoch 967/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.3019
Epoch 968/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.3019
Epoch 969/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.3019
Epoch 970/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 0.3019
Epoch 971/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3019
Epoch 972/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.3019
Epoch 973/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.3018
Epoch 974/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3018
Epoch 975/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3018
Epoch 976/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.

In [ ]:
# 결과
# Prediction for input 5: [[11.932388]]
# Weights: [[2.5671766]]
# Biases: [-0.9034952]

예측값 상수 변경 : 5--> 15

In [13]:
import tensorflow as tf

# 데이터 정의
X = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)  # 입력 데이터
y = tf.constant([[2], [4], [6], [10]], dtype=tf.float32)  # 정답 데이터

# 모델 정의
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=[1])  # 출력 뉴런 1개, 입력 형태는 1차원 데이터
])

# 모델 컴파일
model.compile(optimizer='sgd', loss='mean_squared_error')

# 모델 학습
model.fit(X, y, epochs=1000)

# 예측 수행
test_input = tf.constant([[15]], dtype=tf.float32)
prediction = model.predict(test_input)
print("Prediction for input 15:", prediction)

# 학습된 가중치와 편향 확인
weights, biases = model.layers[0].get_weights()
print("Weights:", weights)
print("Biases:", biases)


Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 340ms/step - loss: 15.8613
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 11.2008
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 7.9664
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 5.7215
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 4.1632
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 3.0813
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 2.3300
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 1.8081
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.4454
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 1.1931
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 1.0175
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.8950
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.8095
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.7495
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.7074
E

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.5115
Epoch 83/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.5102
Epoch 84/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.5090
Epoch 85/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.5077
Epoch 86/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.5065
Epoch 87/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.5053
Epoch 88/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.5040
Epoch 89/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.5028
Epoch 90/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.5016
Epoch 91/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - loss: 0.5004
Epoch 92/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 0.4992
Epoch 93/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 0.4980
Epoch 94/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.4968
Epoch 95/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.4956
Epoch 96/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.4945
Epoch 97/

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.4309
Epoch 163/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.4301
Epoch 164/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.4293
Epoch 165/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.4286
Epoch 166/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.4278
Epoch 167/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.4270
Epoch 168/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.4263
Epoch 169/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 0.4255
Epoch 170/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.4248
Epoch 171/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.4240
Epoch 172/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 0.4233
Epoch 173/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.4226
Epoch 174/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.4218
Epoch 175/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.4211
Epoch 176/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.3810
Epoch 243/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - loss: 0.3805
Epoch 244/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3801
Epoch 245/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3796
Epoch 246/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3791
Epoch 247/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3786
Epoch 248/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.3782
Epoch 249/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3777
Epoch 250/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3772
Epoch 251/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 0.3768
Epoch 252/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.3763
Epoch 253/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3759
Epoch 254/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3754
Epoch 255/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3749
Epoch 256/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3501
Epoch 323/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - loss: 0.3498
Epoch 324/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3496
Epoch 325/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3493
Epoch 326/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3490
Epoch 327/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3487
Epoch 328/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3484
Epoch 329/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3481
Epoch 330/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.3478
Epoch 331/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3475
Epoch 332/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3472
Epoch 333/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3469
Epoch 334/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3467
Epoch 335/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3464
Epoch 336/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3310
Epoch 403/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3309
Epoch 404/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.3307
Epoch 405/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3305
Epoch 406/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 0.3303
Epoch 407/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3301
Epoch 408/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.3299
Epoch 409/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3298
Epoch 410/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3296
Epoch 411/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3294
Epoch 412/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3292
Epoch 413/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3291
Epoch 414/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3289
Epoch 415/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3287
Epoch 416/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3192
Epoch 483/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3191
Epoch 484/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3190
Epoch 485/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3189
Epoch 486/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.3188
Epoch 487/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3186
Epoch 488/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3185
Epoch 489/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3184
Epoch 490/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3183
Epoch 491/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3182
Epoch 492/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3181
Epoch 493/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3180
Epoch 494/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3179
Epoch 495/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3178
Epoch 496/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3119
Epoch 563/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3118
Epoch 564/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 0.3117
Epoch 565/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3117
Epoch 566/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3116
Epoch 567/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3115
Epoch 568/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3115
Epoch 569/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 0.3114
Epoch 570/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3113
Epoch 571/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3113
Epoch 572/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3112
Epoch 573/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3111
Epoch 574/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.3111
Epoch 575/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 0.3110
Epoch 576/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.3074
Epoch 643/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.3073
Epoch 644/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3073
Epoch 645/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3072
Epoch 646/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.3072
Epoch 647/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3071
Epoch 648/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3071
Epoch 649/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3071
Epoch 650/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3070
Epoch 651/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 0.3070
Epoch 652/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3069
Epoch 653/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3069
Epoch 654/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3068
Epoch 655/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3068
Epoch 656/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3046
Epoch 723/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3045
Epoch 724/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3045
Epoch 725/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3045
Epoch 726/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 0.3044
Epoch 727/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 0.3044
Epoch 728/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.3044
Epoch 729/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 0.3044
Epoch 730/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3043
Epoch 731/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.3043
Epoch 732/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.3043
Epoch 733/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 0.3043
Epoch 734/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3042
Epoch 735/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3042
Epoch 736/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3028
Epoch 803/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3028
Epoch 804/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 0.3028
Epoch 805/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 0.3028
Epoch 806/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3028
Epoch 807/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3027
Epoch 808/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3027
Epoch 809/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3027
Epoch 810/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 0.3027
Epoch 811/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3027
Epoch 812/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3027
Epoch 813/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 0.3026
Epoch 814/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3026
Epoch 815/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.3026
Epoch 816/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 0.3017
Epoch 883/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3017
Epoch 884/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 0.3017
Epoch 885/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 0.3017
Epoch 886/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 0.3017
Epoch 887/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3017
Epoch 888/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 0.3017
Epoch 889/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3017
Epoch 890/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 0.3017
Epoch 891/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3017
Epoch 892/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 0.3016
Epoch 893/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3016
Epoch 894/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3016
Epoch 895/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.3016
Epoch 896/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 0.

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.3011
Epoch 963/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.3011
Epoch 964/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3011
Epoch 965/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 0.3011
Epoch 966/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3011
Epoch 967/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 0.3010
Epoch 968/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 0.3010
Epoch 969/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.3010
Epoch 970/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.3010
Epoch 971/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 0.3010
Epoch 972/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 0.3010
Epoch 973/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 0.3010
Epoch 974/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 0.3010
Epoch 975/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3010
Epoch 976/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.

In [ ]:
# 결과
# Prediction for input 15: [[37.70654]]
# Weights: [[2.5756662]]
# Biases: [-0.9284558]

# TensorFlow에서 자주 사용되는 기본 함수

In [14]:
import tensorflow as tf

## tf.constant

In [ ]:
# 용도: 학습 중 변경되지 않는 고정된 값을 정의할 때 사용합니다.

In [21]:
a = tf.constant([1, 2, 3])
b = tf.constant(4.0)

In [22]:
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [23]:
b

<tf.Tensor: shape=(), dtype=float32, numpy=4.0>

## tf.Variable

In [ ]:
# 용도: 모델 파라미터(예: 가중치, 편향)와 같이 학습 과정에서 업데이트되는 값을 정의할 때 사용합니다.

In [ ]:
# weight라는 이름의 학습 가능한 변수 텐서를 생성합니다. 
# tf.Variable과 tf.random.normal 함수를 사용하여 가중치 텐서를 초기화합니다. 

# tf.random.normal 함수는 정규 분포(평균이 0, 표준편차가 1인 분포)를 따르는 임의의 값을 생성합니다.
# [3, 2]는 생성할 텐서의 형태(shape)를 지정합니다. 여기서는 (3, 2) 모양의 2차원 텐서를 생성합니다.
# 따라서, tf.random.normal([3, 2])은 평균이 0이고 표준편차가 1인 정규 분포에서 샘플링된 값들로 이루어진 3x2 텐서를 반환합니다.
# tf.Variable(...):

# tf.Variable은 텐서를 변수로 선언하여 학습 중에 값이 변경될 수 있도록 합니다.
# 이 텐서의 값은 학습 과정에서 업데이트될 수 있으며, 일반적으로 신경망의 가중치(weight)나 편향(bias)와 같은 학습 가능한 파라미터를 정의할 때 사용합니다.

In [24]:
weight = tf.Variable(tf.random.normal([3, 2]))

In [25]:
weight

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float32, numpy=
array([[-0.8490412 , -1.8708192 ],
       [-0.5454401 ,  0.06754289],
       [ 1.1337255 ,  0.1642481 ]], dtype=float32)>

## tf.matmul (행렬 곱셈)

In [ ]:
# 설명: 두 텐서의 행렬 곱셈을 수행합니다
    
# 용도: 신경망의 레이어에서 입력과 가중치를 곱할 때 사용됩니다

### 사례1

In [56]:
import tensorflow as tf

# 두 개의 2x2 행렬
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

# 행렬 곱셈
c = tf.matmul(a, b)
print("Result:\n", c.numpy())


Result:
 [[19 22]
 [43 50]]


In [ ]:
# tf.matmul(a, b)는 행렬 a와 b의 곱셈을 수행합니다.
# 결과는 [[19, 22], [43, 50]]입니다. 각각의 위치에 있는 값은 행렬 곱셈 규칙을 적용하여 계산됩니다.
# 예를 들어, 첫 번째 행과 첫 번째 열의 값은 1*5 + 2*7 = 19로 계산됩니다.

### 사례2

In [ ]:
# 서로 다른 크기의 행렬 곱셈
# tf.matmul은 행렬 곱셈 규칙을 따르므로, 첫 번째 행렬의 열 개수와 두 번째 행렬의 행 개수가 같아야 합니다.

In [57]:
# (2x3) 행렬과 (3x2) 행렬
a = tf.constant([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
b = tf.constant([[7, 8], [9, 10], [11, 12]])  # shape (3, 2)

c = tf.matmul(a, b)
print("Result:\n", c.numpy())


Result:
 [[ 58  64]
 [139 154]]


In [ ]:
# a는 (2, 3) 크기이고, b는 (3, 2) 크기이므로 곱셈이 가능합니다.
# 결과는 (2, 2) 크기의 행렬입니다.
# 첫 번째 위치 값: 1*7 + 2*9 + 3*11 = 58
# 두 번째 위치 값: 1*8 + 2*10 + 3*12 = 64

### 배치 행렬 곱셈

In [ ]:
# TensorFlow에서는 여러 행렬을 동시에 곱셈하는 배치 행렬 곱셈도 가능합니다. 
# 이 경우, 텐서의 첫 번째 차원(batch dimension)이 동일한 경우 여러 행렬 쌍에 대해 곱셈을 수행합니다.

In [58]:
# 두 개의 (2x2) 행렬을 각각 배치로 처리
a = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # shape (2, 2, 2)
b = tf.constant([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # shape (2, 2, 2)

c = tf.matmul(a, b)
print("Result:\n", c.numpy())


Result:
 [[[ 31  34]
  [ 71  78]]

 [[155 166]
  [211 226]]]


In [ ]:
# a와 b는 각각 두 개의 (2, 2) 행렬을 포함하는 (2, 2, 2) 크기의 텐서입니다.
# tf.matmul은 각 배치에 대해 곱셈을 수행하여 두 개의 (2, 2) 결과 행렬을 반환합니다.

## Dense Layer 구현을 위한 행렬 곱셈

In [ ]:
# 신경망에서 완전 연결(Dense) 레이어는 보통 행렬 곱셈으로 구현됩니다. 
# 예를 들어, (batch_size, input_dim) 크기의 입력과 (input_dim, output_dim) 크기의 가중치를 곱하여 (batch_size, output_dim) 크기의 출력을 생성할 수 있습니다.

In [59]:
# 예제 입력 텐서 (batch_size=3, input_dim=4)
inputs = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=tf.float32)

# 가중치 텐서 (input_dim=4, output_dim=2)
weights = tf.constant([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6], [0.7, 0.8]], dtype=tf.float32)

# 행렬 곱을 수행하여 출력 계산
outputs = tf.matmul(inputs, weights)
print("Outputs:\n", outputs.numpy())


Outputs:
 [[ 5.   6. ]
 [11.4 14. ]
 [17.8 22. ]]


In [ ]:
# inputs 텐서는 (3, 4) 크기이고, weights 텐서는 (4, 2) 크기이므로 곱셈이 가능합니다.
# 결과는 (3, 2) 크기의 텐서입니다. 각 위치의 값은 행렬 곱셈 규칙을 따라 계산됩니다.

## tf.add(1), tf.subtract(2), tf.multiply(3), tf.divide(4)

In [ ]:
# 설명: 각각 텐서의 덧셈, 뺄셈, 곱셈, 나눗셈 연산을 수행합니다.
#     용도: 텐서 간의 기본적인 산술 연산을 수행할 때 사용됩니다.

### 텐서 덧셈

스칼라 덧셈

In [60]:
import tensorflow as tf


a = tf.constant(3)
b = tf.constant(5)
c = tf.add(a, b)
print("Result:", c.numpy())
c

Result: 8


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [37]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
result1 = tf.add(a, b) 
result1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9])>

2차원 텐서(행렬) 덧셈

In [61]:
# 2차원 텐서 덧셈
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
c = tf.add(a, b)
print("Result:\n", c.numpy())


Result:
 [[ 6  8]
 [10 12]]


In [ ]:
# 모델 파라미터와 값의 덧셈 (예: 편향 추가)
# 신경망에서 활성화 함수 전의 가중합 계산에서 편향을 추가하는 데 tf.add를 사용할 수 있습니다.

In [62]:
# 가중치 곱과 편향 덧셈
inputs = tf.constant([1.0, 2.0, 3.0])
weights = tf.constant([0.1, 0.2, 0.3])
bias = tf.constant(0.5)

# 가중치 곱을 계산하고 편향 추가
weighted_sum = tf.reduce_sum(tf.multiply(inputs, weights))  # 1.4
output = tf.add(weighted_sum, bias)  # 1.4 + 0.5 = 1.9
print("Output with bias:", output.numpy())


Output with bias: 1.9000001


### 뺄셈

In [38]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
result2 = tf.subtract(a, b) 
result2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-3, -3, -3])>

### 텐서 요소별 곱셈

기본 사용법: 스칼라 곱셈

In [63]:
import tensorflow as tf

# 스칼라 곱셈
a = tf.constant(3)
b = tf.constant(5)
c = tf.multiply(a, b)
print("Result:", c.numpy())


Result: 15


1차원 텐서(벡터) 곱셈

In [64]:
# 1차원 텐서 곱셈
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
c = tf.multiply(a, b)
print("Result:", c.numpy())


Result: [ 4 10 18]


2차원 텐서(행렬) 곱셈

In [65]:
# 2차원 텐서 곱셈
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
c = tf.multiply(a, b)
print("Result:\n", c.numpy())


Result:
 [[ 5 12]
 [21 32]]


브로드캐스팅을 활용한 곱셈

In [ ]:

# tf.multiply는 텐서의 크기가 맞지 않더라도, 브로드캐스팅 규칙을 통해 크기를 맞춰 곱셈을 수행할 수 있습니다.

In [66]:
# 브로드캐스팅을 활용한 곱셈
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.constant([1, 2, 3])
c = tf.multiply(a, b)
print("Result:\n", c.numpy())


Result:
 [[ 1  4  9]
 [ 4 10 18]]


In [ ]:
# a는 (2, 3) 크기, b는 (3,) 크기를 가지며, b의 값이 각 행마다 반복되어 a와 동일한 크기로 브로드캐스팅됩니다.
# 요소별 곱셈 결과는 [[1, 4, 9], [4, 10, 18]]입니다.

신경망에서 가중치 적용 시 사용

In [67]:
# 입력과 가중치의 요소별 곱셈
inputs = tf.constant([1.0, 2.0, 3.0])
weights = tf.constant([0.1, 0.2, 0.3])

# 요소별 곱셈 수행
weighted_inputs = tf.multiply(inputs, weights)
print("Weighted inputs:", weighted_inputs.numpy())

# 가중합 계산
weighted_sum = tf.reduce_sum(weighted_inputs)
print("Weighted sum:", weighted_sum.numpy())


Weighted inputs: [0.1        0.4        0.90000004]
Weighted sum: 1.4000001


In [ ]:
# inputs와 weights를 요소별로 곱하여 [0.1, 0.4, 0.9]를 얻습니다.
# 이후 tf.reduce_sum을 통해 모든 요소의 합을 구해 가중합을 1.4로 계산합니다.

### 나눗셈

기본 사용법: 스칼라 나눗셈

In [68]:
import tensorflow as tf

# 스칼라 나눗셈
a = tf.constant(10)
b = tf.constant(2)
c = tf.divide(a, b)
print("Result:", c.numpy())


Result: 5.0


1차원 텐서(벡터) 나눗셈

In [69]:
# 1차원 텐서 나눗셈
a = tf.constant([10, 20, 30])
b = tf.constant([2, 4, 5])
c = tf.divide(a, b)
print("Result:", c.numpy())


Result: [5. 5. 6.]


2차원 텐서(행렬) 나눗셈

In [70]:
# 2차원 텐서 나눗셈
a = tf.constant([[10, 20], [30, 40]])
b = tf.constant([[2, 5], [3, 8]])
c = tf.divide(a, b)
print("Result:\n", c.numpy())


Result:
 [[ 5.  4.]
 [10.  5.]]


신경망에서 정규화에 활용

In [ ]:
# tf.divide를 사용하여 신경망에서 입력 데이터를 정규화할 수 있습니다. 
# 예를 들어, 이미지를 정규화하여 모든 픽셀 값을 [0, 1] 범위로 변환할 수 있습니다.

In [71]:
# 이미지 정규화
image = tf.constant([[100, 150], [200, 255]], dtype=tf.float32)
normalized_image = tf.divide(image, 255.0)
print("Normalized Image:\n", normalized_image.numpy())


Normalized Image:
 [[0.39215687 0.5882353 ]
 [0.78431374 1.        ]]


In [ ]:
# image는 각 픽셀 값이 0에서 255 사이에 있는 텐서입니다.
# tf.divide를 통해 255.0으로 나누어 [0, 1] 범위로 정규화합니다.
# 정규화된 값은 [[0.392, 0.588], [0.784, 1.0]]이 됩니다.

배치 정규화에 활용

In [ ]:
# 배치 정규화는 딥러닝 모델에서 각 배치마다 평균을 0, 분산을 1로 조정하여 학습을 안정화하는 기법입니다.

## tf.reshape

In [ ]:
# 설명: 텐서의 모양을 변경합니다.
#     용도: 신경망의 입력 크기나 데이터의 모양을 조정할 때 사용됩니다.

In [42]:
a = tf.constant([[1, 2, 3], [4, 5, 6]])
b = tf.reshape(a, [3, 2])  
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [ ]:
# tf.reshape 텐서의 데이터 구조는 유지하면서 모양만 변경할 때 매우 유용합니다.
# 이미지 처리, 차원 확장/축소, 데이터 평탄화 등에서 다양하게 활용됩니다.
# 변환 후의 차원 크기와 원래 차원 크기의 총 요소 수는 항상 같아야 합니다.

In [43]:
import tensorflow as tf

# 1D 텐서 생성
a = tf.constant([1, 2, 3, 4, 5, 6])

# 1D 텐서를 2x3 형태로 변환
reshaped_a = tf.reshape(a, [2, 3])
print("Original:", a.numpy())
print("Reshaped:", reshaped_a.numpy())


Original: [1 2 3 4 5 6]
Reshaped: [[1 2 3]
 [4 5 6]]


## tf.reduce_mean, tf.reduce_sum

In [ ]:
# 설명: 텐서의 특정 차원에 대해 평균 또는 합계를 계산합니다.
#     용도: 손실 함수 계산 시 평균이나 합계를 구할 때 사용됩니다.

In [44]:
a = tf.constant([[1, 2], [3, 4]])
mean = tf.reduce_mean(a)  
sum = tf.reduce_sum(a, axis=0)  


In [46]:
mean

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [45]:
sum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6])>

In [ ]:
## tf.argmax, tf.argmin

## tf.GradientTape

In [ ]:
# 설명: 자동 미분을 위해 그라디언트를 계산하는 함수입니다.
# 용도: 역전파를 통해 손실에 대한 가중치의 기울기를 계산할 때 사용됩니다.

In [47]:
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x ** 2
dy_dx = tape.gradient(y, x)  # dy_dx는 6.0


In [48]:
dy_dx 

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

# 데이터 전처리 관련

## tf.data.Dataset

In [ ]:
# 설명: 데이터 입력 파이프라인을 생성하는 데 사용됩니다.
# 용도: 대용량 데이터를 효율적으로 불러오고 배치 단위로 처리할 때 사용됩니다.

In [ ]:
# dataset을 배치(batch) 단위로 묶는 역할을 합니다. dataset.batch(2)는 TensorFlow의 tf.data.Dataset API에서 데이터를 2개의 샘플씩 배치로 묶는 함수입니다.

# 설명
# dataset.batch(2):
# 데이터셋을 두 개의 샘플(batch size=2)로 묶어서 하나의 배치로 만듭니다.
# 배치 처리를 통해 모델 학습 시 메모리 사용을 최적화하고, 계산 속도를 높일 수 있습니다.
# 예시
# 다음 예제에서, dataset에는 1부터 6까지의 정수가 들어 있으며, batch(2)를 통해 각 배치에 2개의 샘플이 포함됩니다.

In [72]:
import tensorflow as tf

# 예제 데이터셋 생성
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# 2개씩 배치로 묶기
dataset = dataset.batch(2)

# 각 배치 출력
for batch in dataset:
    print(batch.numpy())


[1 2]
[3 4]
[5 6]


In [73]:
import tensorflow as tf

# 예제 데이터셋 생성
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# 3개씩 배치로 묶기
dataset = dataset.batch(3)

# 각 배치 출력
for batch in dataset:
    print(batch.numpy())


[1 2 3]
[4 5 6]


In [ ]:
## 배치 및 셔플

In [ ]:
import tensorflow as tf

# 데이터셋 생성
data = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])

# 데이터 전처리: 배치 및 셔플
data = data.batch(2).shuffle(buffer_size=5).repeat()


In [ ]:
# 주요 메서드:

# batch(batch_size): 데이터를 지정한 크기(batch_size)의 배치로 묶습니다.
# shuffle(buffer_size): 데이터를 무작위로 섞습니다.
# repeat(count): 데이터셋을 지정한 횟수(count)만큼 반복합니다. count를 지정하지 않으면 무한 반복합니다.

## 이미지 데이터 전처리 (tf.image 모듈)

In [ ]:
# tf.image 모듈은 이미지 데이터의 전처리를 위한 다양한 기능을 제공합니다. 
# 주로 이미지 크기 조정, 데이터 증강(augmentation), 색상 변환 등을 수행할 때 사용됩니다

In [ ]:
# 크기 조정: 모델 입력 크기에 맞게 이미지를 조정합니다.

In [ ]:
resized_image = tf.image.resize(image, [128, 128])


In [ ]:
# 정규화: 픽셀 값을 0~1 사이로 조정하여 학습을 안정화합니다

In [ ]:
normalized_image = image / 255.0

In [ ]:
# 데이터 증강: 학습 데이터에 다양성을 주어 모델의 일반화 성능을 높입니다

In [ ]:
flipped_image = tf.image.flip_left_right(image)  # 좌우 반전
rotated_image = tf.image.rot90(image)  # 90도 회전


## 정규화 및 표준화

In [ ]:
# 정규화(Normalization)와 표준화(Standardization)는 데이터의 스케일을 조정하여 학습 안정성을 높입니다. 
# 이 작업은 주로 수치 데이터(예: 시계열 데이터, CSV 파일)에서 수행됩니다.

In [ ]:
#정규화: 데이터를 특정 범위(예: 0~1)로 조정합니다.

In [ ]:
normalized_data = (data - data_min) / (data_max - data_min)


In [ ]:
# 표준화: 데이터를 평균 0, 표준편차 1로 조정합니다.

In [ ]:
standardized_data = (data - data_mean) / data_std


## 배치 정규화 (Batch Normalization)

In [ ]:
# 배치 정규화는 신경망의 각 층에서 입력을 정규화하여 학습을 안정화하는 방법입니다.
# tf.keras.layers.BatchNormalization 레이어를 사용해 쉽게 적용할 수 있습니다.

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3)),
    tf.keras.layers.BatchNormalization(),  # 배치 정규화
    tf.keras.layers.ReLU(),
])


## 학습 데이터와 평가 데이터 나누기

In [ ]:
# 데이터를 학습용과 평가용으로 나누는 것은 필수적인 전처리 작업 중 하나입니다.
# TensorFlow에서는 tf.data.Dataset의 take와 skip을 사용해 이를 쉽게 구현할 수 있습니다.

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(data)
train_data = dataset.take(80)  # 처음 80%를 학습 데이터로 사용
test_data = dataset.skip(80)   # 나머지 20%를 평가 데이터로 사용


## 텍스트 데이터 전처리 (tf.keras.preprocessing.text 모듈)

In [ ]:
# 텍스트 데이터를 다룰 때는 토큰화, 정수 인코딩, 패딩, 시퀀스 길이 조정 등이 필요합니다. 
# 이 작업은 주로 NLP 모델의 입력으로 준비할 때 사용됩니다.

### 토큰화 및 인코딩

In [ ]:
Tokenizer 클래스를 사용해 문장을 단어 또는 문자 수준에서 토큰화하고 정수로 인코딩할 수 있습니다.

In [78]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = ["I love TensorFlow", "TensorFlow is great"]
tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)


### 패딩

In [79]:
# 문장의 길이가 다를 경우, pad_sequences를 사용해 동일한 길이로 맞춥니다.

In [80]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_sequences = pad_sequences(sequences, maxlen=5, padding='post')


In [ ]:
# sequences: 패딩을 적용할 입력 시퀀스 데이터입니다. 이 데이터는 리스트 형태로, 각 리스트에는 정수로 변환된 시퀀스가 포함됩니다. 예를 들어, [ [1, 2, 3], [4, 5], [6] ]과 같은 형태입니다.
# maxlen=5: 패딩 후의 시퀀스 길이를 지정합니다. 각 시퀀스는 패딩을 통해 길이가 최대 5가 되도록 조정됩니다. 만약 시퀀스가 5보다 길면, 5개만 남기고 나머지는 잘라냅니다.
# padding='post': 패딩을 추가하는 위치를 지정합니다. 'post'는 시퀀스의 뒤쪽에 패딩을 추가하는 옵션이며, 'pre'로 설정하면 앞쪽에 패딩을 추가합니다.

In [ ]:
# 예를 들어, 다음과 같은 시퀀스가 있을 때:

In [82]:
sequences = [[1, 2, 3], [4, 5], [6]]
pad_sequences(sequences, maxlen=5, padding='post')

array([[1, 2, 3, 0, 0],
       [4, 5, 0, 0, 0],
       [6, 0, 0, 0, 0]])

In [ ]:
# 설명
# 첫 번째 시퀀스 [1, 2, 3]은 길이가 3이므로 뒤에 0을 두 번 추가하여 [1, 2, 3, 0, 0]이 됩니다.
# 두 번째 시퀀스 [4, 5]는 길이가 2이므로 뒤에 0을 세 번 추가하여 [4, 5, 0, 0, 0]이 됩니다.
# 세 번째 시퀀스 [6]은 길이가 1이므로 뒤에 0을 네 번 추가하여 [6, 0, 0, 0, 0]이 됩니다.

제로 패딩

In [ ]:
# 제로 패딩(Zero Padding)은 시퀀스의 길이를 맞추거나 컨볼루션 레이어에서 출력 크기를 유지하기 위해 0으로 패딩을 추가하는 기법입니다.

텍스트 데이터에서 제로 패딩

In [ ]:
.# TensorFlow에서는 pad_sequences 함수를 사용해 제로 패딩을 간편하게 적용할 수 있습니다.

In [83]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 예시 시퀀스 (길이가 서로 다름)
sequences = [[1, 2, 3], [4, 5], [6]]

# 제로 패딩 적용 (길이를 5로 맞추고, 뒤쪽에 0을 추가)
padded_sequences = pad_sequences(sequences, maxlen=5, padding='post', value=0)

print("제로 패딩된 시퀀스:\n", padded_sequences)


제로 패딩된 시퀀스:
 [[1 2 3 0 0]
 [4 5 0 0 0]
 [6 0 0 0 0]]


In [ ]:
# maxlen=5로 지정하여 각 시퀀스의 길이가 5가 되도록 합니다.
# padding='post'로 뒤쪽에 0을 추가하여 제로 패딩을 수행합니다.
# 결과적으로 길이가 5로 맞춰진 배열을 얻게 됩니다.

이미지 데이터에서 제로 패딩 (컨볼루션 레이어)

In [ ]:
# 컨볼루션 신경망(CNN)**에서 제로 패딩을 사용하면 입력 이미지 주변에 0으로 된 픽셀을 추가하여 출력 크기를 조절하거나 유지할 수 있습니다. 
# 제로 패딩은 주로 Conv2D 레이어에서 padding='same'으로 지정하여 자동으로 적용할 수 있습니다.

In [84]:
import tensorflow as tf

# 3x3 이미지 생성 (예: 흑백 이미지)
image = tf.constant([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]], dtype=tf.float32)
image = tf.reshape(image, (1, 3, 3, 1))  # 배치 차원과 채널 추가: (1, 3, 3, 1)

# Conv2D 레이어에 제로 패딩 적용
conv_layer = tf.keras.layers.Conv2D(filters=1, kernel_size=(3, 3), padding='same')
output = conv_layer(image)

print("입력 이미지 크기:", image.shape)
print("출력 이미지 크기:", output.shape)


입력 이미지 크기: (1, 3, 3, 1)
출력 이미지 크기: (1, 3, 3, 1)


In [ ]:
# padding='same'으로 설정하여 Conv2D 레이어에서 제로 패딩을 적용했습니다.
# 제로 패딩을 통해 출력 크기가 입력 이미지 크기 (3, 3)와 동일하게 유지됩니다.
# 컨볼루션 레이어는 원래 이미지의 가장자리를 보완하기 위해 자동으로 0을 채워 넣어 연산을 수행합니다.

수동 제로 패딩 예시

In [ ]:
# TensorFlow의 tf.pad 함수를 사용하여 수동으로 0을 추가할 수도 있습니다

In [85]:
import tensorflow as tf

# 3x3 텐서 (예시 데이터)
tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 위, 아래, 왼쪽, 오른쪽에 각각 1픽셀의 0 패딩 추가
padded_tensor = tf.pad(tensor, [[1, 1], [1, 1]], mode='CONSTANT', constant_values=0)

print("제로 패딩된 텐서:\n", padded_tensor.numpy())


제로 패딩된 텐서:
 [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


In [ ]:
# tf.pad 함수에 [[1, 1], [1, 1]]을 인자로 주어, 위/아래, 왼쪽/오른쪽에 각각 1픽셀 두께의 제로 패딩을 추가했습니다.
# mode='CONSTANT'와 constant_values=0을 통해 패딩 값이 0으로 설정되었습니다.

## 기타 전처리 도구: tf.keras.utils


In [ ]:
# tf.keras.utils.to_categorical: 정수형 레이블을 원-핫 인코딩으로 변환합니다. 
#     예를 들어, 다중 클래스 분류에서 클래스 레이블을 원-핫 벡터로 변환할 때 유용합니다.

In [ ]:
from tensorflow.keras.utils import to_categorical

labels = [0, 1, 2]
one_hot_labels = to_categorical(labels, num_classes=3)


In [ ]:
# tf.keras.utils.normalize: 배열을 정규화하여 0과 1 사이의 값으로 변환합니다.

In [ ]:
normalized_data = tf.keras.utils.normalize(data)


## tf.function

In [ ]:
# 설명: 파이썬 함수를 TensorFlow 그래프로 변환하여 실행 속도를 높입니다.

# 용도: 반복적으로 호출되는 계산을 최적화하여 성능을 향상할 때 사용됩니다.

In [53]:
@tf.function
def f(x, y):
    return x * y
result = f(2, 3)  


In [54]:
result

<tf.Tensor: shape=(), dtype=int32, numpy=6>

신경망 모델에서 tf.function 사용

In [74]:
# 가중치와 편향 정의
weights = tf.Variable([[0.1, 0.2], [0.3, 0.4]])
bias = tf.Variable([0.1, 0.2])

# @tf.function으로 그래프 모드 변환
@tf.function
def neural_network(x):
    return tf.matmul(x, weights) + bias

# 입력 데이터 정의
inputs = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# 예측 실행
output = neural_network(inputs)
print("Output:\n", output.numpy())


Output:
 [[0.8000001 1.2      ]
 [1.6       2.4      ]]


In [ ]:
# @tf.function을 사용하여 neural_network 함수를 그래프 모드로 변환했습니다.
# tf.matmul 연산이 빠른 그래프 연산으로 최적화되어 실행됩니다.
# neural_network 함수는 가중치와 편향을 사용해 예측을 수행합니다.

학습 루프에서 tf.function 사용하기

In [75]:
# 가중치와 학습률 정의
weights = tf.Variable(1.0)
learning_rate = 0.01

# 손실 함수
def compute_loss(x, y):
    y_pred = x * weights
    return tf.reduce_mean((y_pred - y) ** 2)

# @tf.function을 사용한 학습 단계 정의
@tf.function
def train_step(x, y):
    with tf.GradientTape() as tape:
        loss = compute_loss(x, y)
    gradients = tape.gradient(loss, [weights])
    weights.assign_sub(learning_rate * gradients[0])
    return loss

# 훈련 데이터 정의
x_train = tf.constant([1.0, 2.0, 3.0, 4.0])
y_train = tf.constant([2.0, 4.0, 6.0, 8.0])

# 학습 루프
for epoch in range(100):
    loss = train_step(x_train, y_train)
    if epoch % 20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.numpy()}")

print("Trained weight:", weights.numpy())


Epoch 0, Loss: 7.5
Epoch 20, Loss: 0.011267285794019699
Epoch 40, Loss: 1.692865407676436e-05
Epoch 60, Loss: 2.5496280642300917e-08
Epoch 80, Loss: 3.807443249570497e-11
Trained weight: 1.9999996


In [ ]:
# train_step 함수에 @tf.function을 적용하여 학습 단계가 그래프 모드로 실행됩니다.
# tf.GradientTape를 사용해 손실에 대한 가중치의 기울기를 계산하고, 가중치를 업데이트합니다.
# 최적화된 학습 루프를 통해 가중치가 목표 값인 2.0에 가까워집니다.

조건문과 반복문을 포함하는 함수

In [ ]:
# tf.function으로 그래프 모드에서 조건문과 반복문을 사용할 수 있습니다. 
# 아래는 조건문과 반복문을 포함한 예시입니다.

In [76]:
@tf.function
def custom_function(x):
    result = 0
    # 조건문 사용
    if x > 0:
        result = x * 2
    else:
        result = x * -2

    # 반복문 사용
    for i in range(5):
        result += i
    return result

# 함수 호출
output = custom_function(tf.constant(3))
print("Output:", output.numpy())


Output: 16


# 모델 구축 관련 함수

## tf.keras.Sequential

In [ ]:
# 설명: 모델의 레이어를 순차적으로 쌓아 신경망을 구성합니다.
# 용도: 심층 신경망 모델을 정의하고 학습할 때 사용합니다

In [55]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(10)
])


In [ ]:
# 1. tf.keras.Sequential([...])
# Sequential 모델은 레이어를 순차적으로 쌓아 올려 만드는 신경망입니다.
# 이 모델에서는 두 개의 Dense 레이어가 순서대로 연결되어 있습니다.

# 2. 첫 번째 레이어: tf.keras.layers.Dense(64, activation='relu')
# Dense(64)는 출력 뉴런의 수가 64인 완전 연결 레이어를 의미합니다.
# 입력 크기는 자동으로 감지되며, 데이터가 들어오면 이전 레이어의 출력 크기(또는 input_shape 매개변수를 통해)로 결정됩니다.
# activation='relu'는 이 레이어가 ReLU 활성화 함수를 사용함을 의미합니다. ReLU(Rectified Linear Unit) 활성화 함수는 음수를 0으로 변환하고, 양수는 그대로 유지하는 비선형 함수로, 딥러닝에서 자주 사용됩니다.
# 이 레이어는 입력 데이터를 64개의 뉴런으로 변환하여 다음 레이어로 전달합니다.

# 3. 두 번째 레이어: tf.keras.layers.Dense(10)
# Dense(10)은 출력 뉴런의 수가 10인 완전 연결 레이어입니다.
# 활성화 함수가 지정되지 않았으므로, 기본적으로 선형 활성화 함수(linear)가 적용됩니다.
# 이 레이어는 일반적으로 출력 레이어로 사용됩니다. 10개의 뉴런을 가지므로, 10가지 클래스를 분류하는 문제(예: 손글씨 숫자 분류의 경우 0-9)에서 사용하기 적합합니다.
# 분류 문제에서는 softmax 활성화 함수를 추가하여 확률로 해석할 수도 있습니다.
# 예를 들어 tf.keras.layers.Dense(10, activation='softmax')로 변경하면, 출력이 각 클래스에 대한 확률로 변환됩니다.

## tf.keras.layers

In [ ]:
# 설명: 딥러닝 모델의 레이어를 정의하는 모듈입니다. Dense, Conv2D, LSTM 등 다양한 레이어가 포함되어 있습니다.

### Dense 레이어 (Fully Connected Layer)

In [ ]:
# Dense 레이어는 완전 연결층으로, 모든 입력 뉴런이 모든 출력 뉴런과 연결된 구조입니다. 
# 주로 **다층 퍼셉트론(MLP)**이나 신경망의 마지막 출력층에서 사용됩니다.

In [ ]:
tf.keras.layers.Dense(units, activation=None, ...)


In [ ]:
# units: 출력 뉴런의 수(즉, 출력 차원). 예를 들어, 분류 문제에서 클래스 수에 따라 설정합니다.
# activation: 활성화 함수 (예: 'relu', 'sigmoid', 'softmax' 등). 기본값은 None으로, 활성화 함수를 지정하지 않으면 선형 활성화가 사용됩니다.

In [ ]:
layer = tf.keras.layers.Dense(64, activation='relu')


In [ ]:
# # 입력이 64개의 뉴런을 통해 활성화 함수 ReLU를 거쳐 다음 레이어로 전달됩니다.
# 용도:

# 다층 퍼셉트론의 기본 구성 요소
# 출력층으로 자주 사용되며, 특히 분류 문제에서 클래스 수에 맞는 Dense 레이어를 추가해 확률로 변환 (softmax 활성화)

 ### Conv2D 레이어 (2D Convolutional Layer)

In [ ]:
# Conv2D 레이어는 2D 컨볼루션 레이어로, 이미지나 영상과 같은 2차원 데이터에서 특징을 추출하는 데 사용됩니다. 
# 이 레이어는 필터(커널)를 사용하여 입력 데이터의 특정 패턴이나 특징을 감지합니다.

In [ ]:
tf.keras.layers.Conv2D(filters, kernel_size, strides=(1, 1), padding='valid', activation=None, ...)


In [ ]:
# filters: 필터의 개수(출력 채널 수). 이 값이 클수록 다양한 특징을 추출할 수 있습니다.
# kernel_size: 필터의 크기(예: (3, 3)). 이미지의 특정 패턴을 감지하는 데 사용되는 윈도우 크기입니다.
# strides: 필터가 이동하는 간격. 기본값은 (1, 1)이며, 값을 늘리면 특성 맵이 줄어듭니다.
# padding: 'valid' (패딩 없음) 또는 'same' (입력과 같은 크기의 출력을 유지하기 위한 제로 패딩) 중 선택합니다.
# activation: 활성화 함수 (예: 'relu', 'sigmoid', 'tanh' 등). 기본값은 None입니다.

### LSTM 레이어 (Long Short-Term Memory Layer)

In [ ]:
# LSTM은 장단기 메모리 네트워크로, 시계열 데이터와 같은 순차적인 데이터에서 패턴을 학습하는 **순환 신경망(RNN)**의 일종입니다. 
# LSTM은 장기 의존성을 학습할 수 있도록 설계되어, 텍스트 생성, 번역, 음성 인식 등에서 자주 사용됩니다.

In [ ]:
tf.keras.layers.LSTM(units, activation='tanh', recurrent_activation='sigmoid', return_sequences=False, ...)


In [ ]:
# units: LSTM 레이어의 유닛 수 (출력 차원). LSTM 셀 내의 메모리 유닛 수를 결정하며, 유닛이 많을수록 더 복잡한 패턴을 학습할 수 있습니다.
# activation: 셀 상태를 계산할 때 사용하는 활성화 함수. 기본값은 'tanh'입니다.
# recurrent_activation: 반복 계산을 수행할 때의 활성화 함수로, 기본값은 'sigmoid'입니다.
# return_sequences: True로 설정하면 모든 시퀀스의 출력을 반환하고, False로 설정하면 마지막 타임스텝의 출력만 반환합니다.

In [ ]:
layer = tf.keras.layers.LSTM(128, return_sequences=True)


In [ ]:
# 128개의 유닛을 가진 LSTM 레이어로, 시퀀스 데이터의 모든 타임스텝의 출력을 반환합니다.
# 용도:

# 시계열 데이터 처리: 예를 들어, 주가 예측, 날씨 예측 등 시간 흐름에 따른 데이터를 학습
# 자연어 처리(NLP): 텍스트 생성, 번역, 감성 분석 등 순차적 데이터가 중요한 문제에서 사용
# 음성 인식: 소리와 같은 순차적 데이터에서 패턴을 학습하여 음성을 텍스트로 변환하는 데 사용

## tf.keras.Model

In [ ]:
# 설명: 복잡한 모델을 구성할 때 사용하는 클래스입니다. 
# 함수형 API와 함께 다양한 입력, 출력 구조를 지원합니다.

In [ ]:
inputs = tf.keras.Input(shape=(32,))
outputs = tf.keras.layers.Dense(1)(inputs)
model = tf.keras.Model(inputs=inputs, outputs=outputs)


# 모델 학습 관련 함수

## model.compile

In [ ]:
# 설명: 모델 학습 전에 손실 함수, 옵티마이저, 평가 지표를 설정하는 함수입니다.

In [ ]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])


## model.fit

In [ ]:
# 설명: 모델을 학습시키는 함수로, 데이터와 에포크 수를 지정하여 학습을 시작합니다.
# 예시

In [ ]:
history = model.fit(train_data, train_labels, epochs=10, batch_size=32)


## model.evaluate

In [ ]:
설명: 학습된 모델의 성능을 평가하는 함수입니다.

In [ ]:
loss, accuracy = model.evaluate(test_data, test_labels)


## model.predict

In [ ]:
# 설명: 모델을 통해 새로운 데이터에 대한 예측을 수행하는 함수입니다.

In [ ]:
predictions = model.predict(new_data)


# 정규화 및 초기화

## tf.keras.initializers

In [ ]:
# 설명: 신경망의 가중치를 초기화하는 다양한 방법을 제공합니다. 
# 일반적으로 Glorot 초기화나 He 초기화를 자주 사용합니다.

In [ ]:
initializer = tf.keras.initializers.HeNormal()
layer = tf.keras.layers.Dense(64, kernel_initializer=initializer)


## tf.keras.regularizers

In [ ]:
#과적합을 방지하기 위해 가중치에 정규화 항을 추가하는 데 사용됩니다.
# L1, L2 정규화 등이 포함됩니다.

In [ ]:
layer = tf.keras.layers.Dense(64, kernel_regularizer=tf.keras.regularizers.l2(0.01))


# 학습률 스케줄링과 조정

## tf.keras.callbacks

In [ ]:
# 설명: 학습률 조정, 조기 종료, 체크포인트 저장 등 학습 중 특정 조건에서 자동으로 동작하는 기능을 제공합니다.

In [ ]:
# 학습률 감소 스케줄러 사용
lr_schedule = tf.keras.callbacks.LearningRateScheduler(lambda epoch: 0.001 * 0.9 ** epoch)
model.fit(train_data, train_labels, epochs=20, callbacks=[lr_schedule])


## EarlyStopping 콜백

In [ ]:
# 설명: 모델 학습이 진행 중 특정 평가 지표가 향상되지 않으면 학습을 자동으로 종료합니다.

In [ ]:
early_stopping = tf.keras.callbacks.EarlyStopping(patience=3, restore_best_weights=True)
model.fit(train_data, train_labels, epochs=20, callbacks=[early_stopping])


# 시각화와 최종 출력

## 학습 과정 시각화: matplotlib을 활용한 정확도 및 손실 그래프

In [ ]:
# 모델의 학습이 진행되면서 손실과 정확도 등이 어떻게 변하는지 확인하기 위해 matplotlib을 사용하여 그래프를 그릴 수 있습니다. 
# model.fit 함수는 학습 과정의 기록을 반환하는 history 객체를 제공하므로 이를 활용합니다.

### 학습 정확도와 손실 시각화

In [ ]:
# history.history['accuracy']: 각 에포크에서의 훈련 데이터에 대한 정확도
# history.history['val_accuracy']: 각 에포크에서의 검증 데이터에 대한 정확도
# history.history['loss']: 각 에포크에서의 훈련 데이터에 대한 손실
# history.history['val_loss']: 각 에포크에서의 검증 데이터에 대한 손실

In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt

# 예시 모델 생성
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(784,)),
    tf.keras.layers.Dense(10, activation='softmax')
])

# 모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# 데이터셋 준비 (예: MNIST)
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = x_train.reshape(-1, 784).astype("float32") / 255.0
x_test = x_test.reshape(-1, 784).astype("float32") / 255.0

# 모델 학습
history = model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))

# 학습 정확도와 손실 시각화
plt.figure(figsize=(12, 4))

# 정확도 그래프
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Training and Validation Accuracy')

# 손실 그래프
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.title('Training and Validation Loss')

plt.show()


## 모델 최종 출력 (예측 수행)

In [ ]:
# 모델이 학습된 후, 새로운 데이터에 대해 예측을 수행할 수 있습니다. 
# 최종 출력은 model.predict 함수를 사용하여 예측값을 구할 수 있습니다.

### 예측 수행 및 결과 출력

In [ ]:
# 새로운 입력 데이터 예시 (MNIST 테스트 데이터 중 일부 샘플)
sample_input = x_test[:5]  # 테스트 데이터에서 처음 5개 샘플 선택

# 예측 수행
predictions = model.predict(sample_input)

# 예측 결과 출력
print("Predictions:\n", predictions)  # 각 클래스에 대한 확률 분포
print("Predicted labels:", tf.argmax(predictions, axis=1).numpy())  # 가장 높은 확률의 클래스


In [ ]:
# model.predict: sample_input에 대한 예측을 수행합니다. predictions는 각 클래스에 대한 확률 분포를 출력합니다.
# tf.argmax(predictions, axis=1): 예측 확률이 가장 높은 클래스의 인덱스를 반환하여, 최종 예측 레이블을 구합니다.
# 예를 들어, MNIST 데이터셋에서는 0~9 사이의 숫자를 예측하므로, 예측 결과로 각 샘플이 어떤 숫자인지 반환됩니다.

### 예측 결과 시각화

In [ ]:
# 이미지 데이터와 함께 예측된 결과를 시각화할 수 있습니다. 
# 이를 통해 모델이 예측한 결과가 맞는지 시각적으로 확인할 수 있습니다.

In [ ]:
# 처음 5개의 테스트 샘플에 대한 예측 및 시각화
num_samples = 5
plt.figure(figsize=(10, 4))

for i in range(num_samples):
    plt.subplot(1, num_samples, i + 1)
    plt.imshow(x_test[i].reshape(28, 28), cmap='gray')
    plt.title(f"Label: {y_test[i]},\nPred: {tf.argmax(predictions[i]).numpy()}")
    plt.axis('off')

plt.show()


In [ ]:
# plt.imshow(x_test[i].reshape(28, 28), cmap='gray'): 각 테스트 샘플 이미지를 회색조로 표시합니다.
# plt.title(f"Label: {y_test[i]}, Pred: {tf.argmax(predictions[i]).numpy()}"): 실제 레이블(y_test[i])과 모델이 예측한 레이블(Pred)을 타이틀로 표시합니다.
# 이 시각화를 통해 모델의 예측이 얼마나 정확한지 확인할 수 있습니다.